const {Workbench,hex}=EE4002;const lab=new Workbench();const $=id=>document.getElementById(id);
const hooks={render:[],task:[],action:[],update:[]};
let renderPending=false,ready=false;
function emit(kind,...args){for(const fn of hooks[kind]){try{fn(...args);}catch(error){console.error('Lab UI '+kind,error);message('Display update failed: '+error.message);$('message').className='error';}}}
function render(){if(!ready||renderPending)return;renderPending=true;requestAnimationFrame(()=>{renderPending=false;try{renderBase();}catch(error){console.error('Lab base display',error);message('Display update failed: '+error.message);$('message').className='error';}emit('render');emit('update');});}
function runAction(id,f){try{f();emit('action',id);update();}catch(error){message(error.message);$('message').className='error';emit('update');render();}}
const safe=f=>event=>runAction(event?.currentTarget?.id||'operation',f);
function message(s){$('message').textContent=s;$('message').className='';}
function encoded(){return (+$('en').value<<7)|(+$('gain').value<<4)|(+$('mux').value<<2)|+$('rate').value;}
let lastSampleCount=-1,lastEventCount=-1;
function renderBase(){const b=encoded();$('encoded').textContent=hex(b)+' / '+b.toString(2).padStart(8,'0');$('levelValue').textContent=lab.level.toFixed(2)+' m';$('current').textContent=lab.current.toFixed(3)+' mA';$('voltage').textContent=(lab.current*.15).toFixed(3)+' V';$('ref').textContent=lab.ref.toFixed(3)+' V';$('dacV').textContent=(lab.dac*3.3/4096).toFixed(6)+' V';$('actualConfig').textContent=hex(lab.config);$('raw').textContent=lab.code+' / '+hex(lab.code,3);$('status').textContent=hex(lab.status);$('time').textContent='Simulation time: '+lab.time.toFixed(1)+' ms';$('savedCount').textContent=lab.saved.length+' checkpoints saved';const flags=['DRDY','OVERRANGE','SETTLING','REF_ERROR','SPI_ERROR','OVERRUN'].filter((x,i)=>lab.status&(1<<i));$('flags').textContent=(lab.enabled?'Enabled':'Stopped')+' · '+(flags.join(', ')||'No flags');const s=lab.samples.at(-1);if(s){$('rawTag').textContent=s.raw_code;$('vinTag').textContent=formatNumber(s.reconstructed_voltage_V,6)+' V';$('levelTag').textContent=s.channel===0?formatNumber(s.tag_level_m,4)+' m':'N/A: channel is not the tank shunt';$('ageTag').textContent=s.source_age_ms+' ms / '+s.sim_time_ms+' ms';}else{['rawTag','vinTag','levelTag','ageTag'].forEach(id=>$(id).textContent='—');} if(lastSampleCount!==lab.samples.length){$('history').replaceChildren(...lab.samples.slice(-15).reverse().map(s=>row([s.sample_id,s.sim_time_ms,s.channel,s.raw_code,s.status,s.settled?'Yes':'No'])));lastSampleCount=lab.samples.length;}if(lastEventCount!==lab.events.length){$('transactions').replaceChildren(...lab.events.filter(e=>e.type==='SPI').slice(-12).reverse().map(e=>row([e.event_id,e.sim_time_ms,e.mode,e.tx,e.rx])));lastEventCount=lab.events.length;}draw();}
function row(values){const tr=document.createElement('tr');values.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});return tr;}
function draw(){const canvas=$('trend'),w=canvas.clientWidth,h=240,dpr=window.devicePixelRatio||1;if(w<1)return;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);c.font='14px Arial';c.fillStyle='#243e50';c.fillText('ADC code',12,20);c.fillText('Simulation time (ms)',Math.max(65,w-170),233);const l=60,r=w-20,t=32,b=195;c.strokeStyle='#c7d2db';[0,2048,4095].forEach(v=>{const y=b-v/4095*(b-t);c.beginPath();c.moveTo(l,y);c.lineTo(r,y);c.stroke();c.fillText(v,7,y+5);});const ss=lab.samples.slice(-30);if(!ss.length)return;const min=ss[0].sim_time_ms,max=Math.max(min+1,ss.at(-1).sim_time_ms);c.fillText(Math.round(min),l,216);c.fillText(Math.round(max),Math.max(l+48,r-42),216);c.strokeStyle='#147489';c.lineWidth=2;c.beginPath();ss.forEach((s,i)=>{const x=l+(s.sim_time_ms-min)/(max-min)*(r-l),y=b-s.raw_code/4095*(b-t);i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();ss.forEach(s=>{c.fillStyle=s.settled?'#147489':'#b2680d';c.beginPath();c.arc(l+(s.sim_time_ms-min)/(max-min)*(r-l),b-s.raw_code/4095*(b-t),4,0,Math.PI*2);c.fill();});}
['en','gain','mux','rate'].forEach(id=>$(id).onchange=safe(()=>{}));
$('level').oninput=safe(()=>{lab.level=+$('level').value;});$('pot').onchange=safe(()=>{const v=+$('pot').value;if(!Number.isFinite(v)||v<0||v>3.3)throw Error('Test voltage must be 0–3.3 V.');lab.pot=v;});$('assumed').onchange=safe(()=>{lab.assumedRef=+$('assumed').value;message('Software assumption changed. Acquire a new sample to reconstruct with it.');});$('fault').onchange=safe(()=>{lab.setFault($('fault').value);message('Fault scenario changed. Existing evidence is preserved.');});$('spi').onchange=safe(()=>lab.spiMode=+$('spi').value);
$('copy').onclick=safe(()=>$('config').value=hex(encoded()));$('write').onclick=safe(()=>{const str=$('config').value.trim();if(!/^(0x[0-9a-f]{1,2}|\d{1,3})$/i.test(str))throw Error('Use a byte such as 0x81 or decimal 129.');lab.write(1,Number(str));message('Write sent. Read CONFIG to verify the accepted state.');});$('idRead').onclick=safe(()=>$('readback').textContent='ID = '+hex(lab.read(0)));$('configRead').onclick=safe(()=>$('readback').textContent='CONFIG read-back = '+hex(lab.read(1)));$('statusRead').onclick=safe(()=>$('readback').textContent='STATUS read-back = '+hex(lab.read(2)));$('clear').onclick=safe(()=>{lab.write(2,48);message('Sent W1C mask 0x30 for SPI_ERROR and OVERRUN. Evidence log retained.');});$('dacWrite').onclick=safe(()=>{lab.writeDac(Number($('dac').value));message('DAC write sent. Read its registers, then measure CH2.');});$('dacRead').onclick=safe(()=>$('readback').textContent='DAC = '+((lab.read(5)<<8)|lab.read(6)));
$('step').onclick=safe(()=>{const s=lab.step();message(s?'Output generated. Read STATUS and DATA.':'No conversion: CONFIG.EN is zero.');});$('three').onclick=safe(()=>{for(let i=0;i<3;i++){lab.step();lab.read(2);lab.read(3);lab.read(4);}message('Three periods elapsed; each output and status was recorded and read.');});$('dataRead').onclick=safe(()=>{const hi=lab.read(3),lo=lab.read(4);$('readback').textContent='DATA = '+((hi<<8)|lo)+'; reading DATA_L clears DRDY';});$('reset').onclick=safe(()=>{lab.reset();$('readback').textContent='ICs reset. Read ID and CONFIG again.';message('Reset preserved evidence and faults. Select None to remove a fault.');});$('save').onclick=safe(()=>{if(!$('label').value.trim())throw Error('Give this checkpoint a label.');const record=lab.save($('label').value.trim());Object.assign(record,{assignment:activeTask,learning_phase:LabSteps.plans[activeTask]?.phase||'practice'});message('Checkpoint saved. Export before closing.');});
document.querySelector('#measurement table').createCaption().textContent='Last recorded conversion. Generate a new sample after changing inputs or configuration.';
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=safe(()=>{download('EE4002_Lab1_evidence.json',JSON.stringify(collectLabEvidence(),null,2),'application/json');message('Download requested. Find EE4002_Lab1_evidence.json in your downloads, check it, then upload it yourself to Moodle. Nothing has been submitted by this page.');});$('csv').onclick=safe(()=>{if(!lab.samples.length)throw Error('Generate samples before exporting CSV.');const keys=Object.keys(lab.samples[0]);const quote=x=>'"'+String(x).replaceAll('"','""')+'"';download('EE4002_Lab1_samples.csv',[keys.join(','),...lab.samples.map(s=>keys.map(k=>quote(s[k])).join(','))].join('\n'),'text/csv');message('Sample history exported.');});window.addEventListener('resize',render);

function collectLabEvidence(){return {model:LabConfig.modelName,app_version:LabConfig.appVersion,evidence_schema:LabConfig.evidenceSchema,task_expectations:LabSteps.expectations(),task_titles:Object.fromEntries(Object.entries(LabSteps.plans).map(([k,p])=>[k,p.title])),simulation_only:true,learning_design:'step-by-step practice then independent',predictions:lab.predictions||[],explanations:lab.responses||[],procedure:lab.workflow||null,exported_at:new Date().toISOString(),group:$('group').value,notes:$('notes').value,assets_csv:$('assets').value,flows_csv:$('flows').value,checkpoints:lab.saved,samples:lab.samples,events:lab.events};}

function formatNumber(value,digits){return typeof value==='number'&&Number.isFinite(value)?value.toFixed(digits):'Not available';}
