if(!isTour){
document.body.classList.add('student-workflow');document.querySelector('main').prepend($('guided'));
const order=[...LabSteps.taskKeys(),'Submit'],independent=k=>LabSteps.plans[k]?.phase==='independent';lab.predictions=lab.predictions||[];
const intro=document.createElement('p');intro.className='workflow-instruction';$('guided').prepend(intro);
const nav=$('guided').querySelector('.task-nav');nav.replaceChildren();for(const [label,key]of [['1 · Practice','A'],['2 · Independent work','E'],['3 · Save locally','Submit']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{showTask(key);update();};nav.append(b);}
const chooser=document.createElement('label');chooser.textContent='Current task ';const select=document.createElement('select');select.id='lessonTask';chooser.append(select);nav.after(chooser);select.onchange=()=>{showTask(select.value);update();};
const pred=document.createElement('section');pred.id='predictionBox';pred.innerHTML='<h3>Predict before measuring</h3><label>Your calculation or prediction<textarea id="predictionText" rows="3" placeholder="Include units and reasoning. No model answer is shown here."></textarea></label><button id="recordPrediction">Record prediction</button><p id="predictionState" role="status"></p>';$('guided').append(pred);
$('recordPrediction').onclick=safe(()=>{const value=$('predictionText').value.trim();if(!value){$('predictionState').textContent='Enter a prediction first.';throw Error('Enter a prediction first.');}lab.predictions.push({task:activeTask,text:value,event_count:lab.events.length,sample_count:lab.samples.length,recorded_at:new Date().toISOString()});$('predictionState').textContent='Prediction recorded for export.';});
const labels={bench:'YOU SET · Test input',registers:'YOU SET · Write, then verify',measurement:'OBSERVE · Read code and status',records:'YOU RECORD · Save your evidence'};for(const[id,label]of Object.entries(labels))$(id).querySelector('h2').textContent=label;
hooks.task.push(function(key){document.body.dataset.task=key;document.body.dataset.phase=independent(key)?'independent':key==='Submit'?'submit':'practice';$('watchTour').hidden=independent(key);pred.hidden=!LabSteps.expectations()[key]?.prediction_required;const keys=key==='Submit'?['Submit']:LabSteps.taskKeys(LabSteps.plans[key].phase);select.replaceChildren(...keys.map((k,i)=>{const o=document.createElement('option');o.value=k;o.textContent=(i+1)+' · '+taskData[k].title;return o;}));select.value=key;intro.textContent=independent(key)?'INDEPENDENT WORK · Set inputs and configuration yourself. Use the device reference; prepared settings and expected answers are not provided.':key==='Submit'?'SAVE LOCALLY · Download your work, then upload the file to Moodle yourself. This page does not submit anything.':'PRACTICE · Follow the example and use Prepare fields. Ask questions now; later solve changed cases yourself.';if(key==='G')$('dacWrite').closest('details').open=true;$('prepared').textContent='';$('predictionText').value=lab.predictions.filter(p=>p.task===key).at(-1)?.text||'';$('predictionState').textContent='';});
const details=document.createElement('details');details.id='extraVisual';const summary=document.createElement('summary');summary.textContent='Optional: inspect the full signal visualization';details.append(summary);const visual=$('liveBench');if(visual){visual.before(details);details.append(visual);}
for(const d of $('records').querySelectorAll('details'))if(d.textContent.includes('Assets CSV'))d.dataset.inventory='true';

}
