'use strict';
(function(root){
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),copy=x=>JSON.parse(JSON.stringify(x));
let serial=0;const uid=()=> 'edit'+Date.now().toString(36)+'_'+(++serial);
class LadderEditor{
 constructor(change){this.change=change;this.g=null;this.sel={n:1,b:0,c:-1};this.undoStack=[];this.redoStack=[];this.lastKey='';this.$=id=>document.getElementById(id);this.bind();}
 source(){return JSON.stringify(this.g,null,2);}
 paintPower(){const traces=this.live?.matching?this.live.scan?.ladder||[]:[];for(const el of this.$('ladCanvas').querySelectorAll('[data-lad-n]')){const n=this.g.networks[Number(el.dataset.ladN)],trace=traces.find(t=>t.id===n.id);let on=false;if(el.dataset.ladC!==undefined){const c=n.branches[Number(el.dataset.ladB)][Number(el.dataset.ladC)];on=!!trace?.branches.flatMap(b=>b.components).find(t=>t.id===c.id)?.power;}else if(el.classList.contains('lad-coil'))on=!!trace?.coil.value;el.classList.toggle('powered',on);}}
 setSource(source,emptyPump=false){const p=Lab3.compile(source);this.g=p.ladder?copy(p.ladder):LadderCore.fromLegacy(p);const i=this.g.networks.findIndex(n=>n.coil.tag==='PumpEnable');if(emptyPump)this.g.networks[i].branches=[[]];this.sel={n:i,b:0,c:-1};this.undoStack=[];this.redoStack=[];this.publish();}
 publish(){this.$('code').value=this.source();this.draw();this.change?.();}
 transact(fn){const prior=JSON.stringify(this.g),selection=copy(this.sel);try{fn();}catch(e){this.g=JSON.parse(prior);this.sel=selection;throw e;}if(prior!==JSON.stringify(this.g)){this.undoStack.push(prior);if(this.undoStack.length>40)this.undoStack.shift();this.redoStack=[];}this.publish();}
 undo(redo=false){const from=redo?this.redoStack:this.undoStack,to=redo?this.undoStack:this.redoStack;if(!from.length)return;to.push(JSON.stringify(this.g));this.g=JSON.parse(from.pop());this.sel={n:0,b:0,c:-1};this.publish();}
 act(fn){try{fn();this.$('message').textContent='Offline draft changed. Check and download in STOP to apply.';}catch(e){this.$('message').textContent=e.message;}}
 add(type){this.transact(()=>{const n=this.g.networks[this.sel.n];if(!n)throw Error('Select a network first.');const b=n.branches[this.sel.b];if(b.length>=8)throw Error('A branch supports at most 8 components.');const c={id:uid(),type,tag:type==='TON'?'T1':'StopOK'};if(type==='TON'){const used=this.g.networks.flatMap(n=>n.branches.flat()).filter(c=>c.type==='TON').map(c=>c.tag);c.tag=LadderCore.TIMERS.find(t=>!used.includes(t));if(!c.tag)throw Error('All four timer instances are used.');c.pt=1;}const at=this.sel.c>=0?this.sel.c+1:b.length;b.splice(at,0,c);this.sel.c=at;});}
 addBranch(){this.transact(()=>{const n=this.g.networks[this.sel.n];if(n.branches.length>=4)throw Error('At most four parallel branches.');n.branches.push([]);this.sel.b=n.branches.length-1;this.sel.c=-1;});}
 addNetwork(){this.transact(()=>{if(this.g.networks.length>=12)throw Error('At most 12 networks.');const used=this.g.networks.map(n=>n.coil.tag),tag=LadderCore.MEMORY.find(t=>!used.includes(t))||'M1';this.g.networks.push({id:uid(),phase:'after',branches:[[]],coil:{type:'COIL',tag}});this.sel={n:this.g.networks.length-1,b:0,c:-1};});}
 moveNetwork(delta){this.transact(()=>{const i=this.sel.n,j=i+delta;if(j<0||j>=this.g.networks.length)return;[this.g.networks[i],this.g.networks[j]]=[this.g.networks[j],this.g.networks[i]];this.sel.n=j;});}
 remove(kind){this.transact(()=>{const n=this.g.networks[this.sel.n];if(kind==='network'){this.g.networks.splice(this.sel.n,1);if(!this.g.networks.length)throw Error('Keep at least one network while editing.');this.sel={n:Math.max(0,this.sel.n-1),b:0,c:-1};}else if(kind==='branch'){if(n.branches.length===1)throw Error('Keep one branch, or delete the network.');n.branches.splice(this.sel.b,1);this.sel.b=0;this.sel.c=-1;}else{if(this.sel.c<0)throw Error('Select a contact or timer to delete.');n.branches[this.sel.b].splice(this.sel.c,1);this.sel.c=-1;}});}
 applyProperties(){this.transact(()=>{const n=this.g.networks[this.sel.n];if(this.sel.c>=0){const c=n.branches[this.sel.b][this.sel.c],type=this.$('ladType').value,tag=this.$('ladTag').value;if(type==='TON'&&!LadderCore.TIMERS.includes(tag)||type!=='TON'&&!LadderCore.TAGS.includes(tag))throw Error('Choose a tag compatible with the component.');c.type=type;c.tag=tag;if(type==='TON'){const pt=Number(this.$('ladPT').value);if(!Number.isFinite(pt)||pt<0||pt>60)throw Error('Preset must be 0–60 seconds.');c.pt=pt;}else delete c.pt;}else{n.coil.type=this.$('ladCoilType').value;n.coil.tag=this.$('ladCoilTag').value;n.phase=this.$('ladPhase').value;}});}
 applyParameters(){this.transact(()=>{const p={mode:this.$('paramMode').value};for(const k of ['Kp','Ki','Kd','Tf','Ts'])p[k]=Number(this.$('param'+k).value);this.g.params=p;});}
 bind(){const map={networkUp:()=>this.moveNetwork(-1),networkDown:()=>this.moveNetwork(1),addNO:()=>this.add('NO'),addNC:()=>this.add('NC'),addTON:()=>this.add('TON'),addBranch:()=>this.addBranch(),addNetwork:()=>this.addNetwork(),deleteComponent:()=>this.remove('component'),deleteBranch:()=>this.remove('branch'),deleteNetwork:()=>this.remove('network'),ladUndo:()=>this.undo(),ladRedo:()=>this.undo(true),applyProperties:()=>this.applyProperties(),applyParameters:()=>this.applyParameters()};for(const [id,fn]of Object.entries(map))this.$(id).onclick=()=>this.act(fn);
 this.$('ladCanvas').onclick=e=>{const el=e.target.closest('[data-lad-n]');if(!el)return;this.sel={n:Number(el.dataset.ladN),b:Number(el.dataset.ladB||0),c:Number(el.dataset.ladC??-1)};this.draw();};
 this.$('ladType').onchange=()=>this.tagOptions(this.$('ladType').value);}
 tagOptions(type,selected){const list=type==='TON'?LadderCore.TIMERS:LadderCore.TAGS;this.$('ladTag').innerHTML=list.map(t=>'<option>'+t+'</option>').join('');this.$('ladTag').value=list.includes(selected)?selected:list[0];this.$('timerProperty').hidden=type!=='TON';}
 draw(){if(!this.g)return;const {n:ni,b:bi,c:ci}=this.sel;
 this.$('ladCanvas').innerHTML=this.g.networks.map((n,i)=>'<section class="lad-network '+(i===ni?'selected-network':'')+'"><button class="network-heading" data-lad-n="'+i+'">Network '+(i+1)+' · '+esc(n.coil.tag)+' <small>'+ (n.phase==='before'?'Before':'After')+' state update</small></button><div class="rung"><div class="parallel">'+n.branches.map((b,j)=>'<div class="lad-branch"><button class="branch-select '+(i===ni&&j===bi?'selected':'')+'" title="Select insertion branch" data-lad-n="'+i+'" data-lad-b="'+j+'">'+(j+1)+'</button>'+b.map((c,k)=>'<button class="lad-component '+(i===ni&&j===bi&&k===ci?'selected':'')+'" data-lad-n="'+i+'" data-lad-b="'+j+'" data-lad-c="'+k+'"><span class="symbol">'+(c.type==='NO'?'─| |─':c.type==='NC'?'─|/|─':'[ TON ]')+'</span><strong>'+esc(c.tag)+'</strong><small>'+(c.type==='TON'?'PT '+c.pt+' s':c.type==='NO'?'TRUE contact':'FALSE contact')+'</small></button>').join('')+(b.length?'':'<span class="empty-branch">Select this branch, then add a contact</span>')+'</div>').join('')+'</div><button class="lad-coil '+(i===ni&&ci<0?'selected':'')+'" data-lad-n="'+i+'" data-lad-b="0"><span class="symbol">─('+(n.coil.type==='SET'?'S':n.coil.type==='RESET'?'R':' ')+')─</span><strong>'+esc(n.coil.tag)+'</strong><small>'+n.coil.type+'</small></button></div></section>').join('');
 const n=this.g.networks[ni],c=ci>=0?n.branches[bi][ci]:null;this.$('contactProperties').hidden=!c;this.$('coilProperties').hidden=!!c;this.$('selectionTitle').textContent='Network '+(ni+1)+(c?' · branch '+(bi+1)+' · component '+(ci+1):' · coil / network');
 if(c){this.$('ladType').value=c.type;this.tagOptions(c.type,c.tag);this.$('ladPT').value=c.pt??1;}else{this.$('ladCoilType').value=n.coil.type;this.$('ladCoilTag').value=n.coil.tag;this.$('ladPhase').value=n.phase;}
 for(const k of ['Kp','Ki','Kd','Tf','Ts'])this.$('param'+k).value=this.g.params[k];this.$('paramMode').value=this.g.params.mode;this.$('ladUndo').disabled=!this.undoStack.length;this.$('ladRedo').disabled=!this.redoStack.length;this.$('deleteComponent').disabled=!c;this.paintPower();
 }
 online(scan,matching){this.live={scan,matching};this.paintPower();const key=JSON.stringify([scan?.ladder,matching]);if(key===this.lastKey)return;this.lastKey=key;this.$('onlineLadder').innerHTML=!matching?'<p class="draft-warning">Draft differs from CPU. Download it before comparing this drawing with the process. The last executed network results remain in Last scan.</p>':!scan?.ladder?'<p>Download the LAD program, select RUN and execute a scan to see power flow.</p>':scan.ladder.map(n=>'<div class="online-rung"><strong>'+esc(n.coil.tag)+'</strong>'+n.branches.map(b=>'<div class="online-branch">'+b.components.map(c=>'<span class="online-contact '+(c.power?'powered':'')+'">'+esc(c.type==='NC'?'[/]':c.type==='TON'?'TON':'[ ]')+' '+esc(c.tag)+(c.et===undefined?'':'<small>ET '+c.et.toFixed(2)+' / '+c.pt+' s</small>')+'</span>').join('<span>─</span>')+'</div>').join('')+'<span class="online-contact '+(n.coil.value?'powered':'')+'">('+esc(n.coil.type)+') '+esc(n.coil.tag)+' = '+n.coil.value+'</span></div>').join('');}
}
root.LadderEditor=LadderEditor;
})(globalThis);
