'use strict';
(()=>{
const $=x=>document.getElementById(x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tasks=[
 {id:'P1',title:'Build a rung and commission it',phase:'Guided practice · 12 minutes',steps:['Load the workspace. Network 2 has an empty branch. Click branch 1, then add a NO contact. In Properties choose Auto and Apply. Add a second NO contact for StopOK. Add an NC contact for Trip. This series rung permits the pump only when Auto AND StopOK AND NOT Trip are true.','Select any contact, delete it, then Undo to restore it. Leave the provided TripCause network unchanged. In the PI/PID panel inspect Kp = 50, Ki = 2 and Ts = 0.1 s. Predict the first command at SP = 1.00 m and PV = 0.80 m. Check, Download in STOP, select RUN, press Start and Single scan. Capture the result.','Observe green online power flow, the input snapshot and output. Press field Stop and Single scan. Capture and explain the change. Editing the orange-selected draft does not change the running program until Download.']},
 {id:'P2',title:'Compare P and PI',phase:'Guided practice · 12 minutes',steps:['Load the workspace. In the PI/PID block select MODE P and Apply parameters to draft; leave other values unchanged. Check and Download, select RUN, press Start. Advance 10 s twelve times, then capture at 120 s.','Reload for the same initial condition. Keep MODE PI; Check, Download, RUN, Start, advance to 120 s and capture.','Compare final error, peak level and output effort. Distinguish transient error at 120 s from steady-state offset. Explain why gains from a different plant cannot be copied without checking units and dynamics.']},
 {id:'I1',title:'Tune and test a disturbance',phase:'Independent work · 12 minutes',steps:['Choose two PI parameter sets in the parameter panel. Predict the tradeoff; keep Ts and all initial conditions identical.','For each set reload, change and Apply parameters, Check, Download, RUN and Start. Run to 60 s. Change supply effectiveness to 65%, then run to 120 s and capture.','Compare both records. Recommend a setting using measured error after the disturbance, peak level and time spent near the output limit. Explain one limitation of your 120 s observation.']},
 {id:'I2',title:'Repair a permission defect',phase:'Independent work · 12 minutes',steps:['Load the faulty ladder program and predict its behavior. Check and Download, RUN, Start, then Single scan. Compare the online contacts with StopOK, Auto, Trip and PumpEnable. Capture before editing.','Select and repair the incorrect contact using Properties. CPU STOP, Check and Download. Repeat healthy StopOK, pressed Stop and released Stop tests; after releasing Stop, apply a fresh Start before expecting AUTO. Capture repair and regression evidence.','Test held Start recovery: hold Start, set level to 1.60 m, single scan; set level to 0.70 m, press Reset, single scan. Keep Start held for more scans, then release it, scan, press Start and scan. Explain the restart sequence. Optional challenge: add a TON after Auto in the PumpEnable branch, preset 1 s, and prove both the delay and its reset on Stop.']},
 {id:'X1',title:'Cascade flow and level control',phase:'Optional extension · after core work',steps:['Compare MODE PI with MODE CASCADE in the parameter panel (click Apply parameters for each change) using identical gains and initial conditions. The cascade outer output is an inlet-flow target, not the final pump command.','For each run apply 65% supply effectiveness at 60 s and capture at 120 s. Observe inlet flow as well as tank level and pump command.','Explain where the extra flow sensor helps, what saturation still prevents, and why the inner loop must be established before tuning the outer loop. Inner-loop gains are fixed in this teaching release.']}
];
let workspaceTask=null;
let plc=new Lab3.PLC(),index=0,playing=false,work={},student='',timer=null,acc=0,ladderEditor=null;
try{const saved=JSON.parse(localStorage.getItem('ee4002-lab3-v1')||'null');if(saved?.schema===1){student=typeof saved.student==='string'?saved.student:'';for(const t of tasks){const w=saved.work?.[t.id];if(w)work[t.id]={prediction:typeof w.prediction==='string'?w.prediction:'',explanation:typeof w.explanation==='string'?w.explanation:'',records:Array.isArray(w.records)?w.records.filter(r=>r&&typeof r.program==='string'&&r.snapshot).slice(-12):[]};}}}catch{ $('message').textContent='A stored draft could not be read. New work can still be downloaded.'; }
const entry=()=>work[tasks[index].id]||(work[tasks[index].id]={prediction:'',explanation:'',records:[]});
work=Lab3Evidence.compactWork(work);
for(const t of tasks){const g=Lab3Guide[t.id];if(!g||g.where.length!==t.steps.length||g.observe.length!==t.steps.length)throw Error('Task guidance mismatch: '+t.id);}
function persist(){clearTimeout(timer);timer=setTimeout(()=>{try{localStorage.setItem('ee4002-lab3-v1',Lab3Evidence.serialize(student,work));$('draftStatus').textContent='Captured work saved locally.';}catch{$('draftStatus').textContent='Local storage full/unavailable. Download evidence now.';}},400);}
function safe(fn){try{fn();}catch(e){$('message').textContent=e.message;}render();}
function select(i){workspaceTask=null;index=i;playing=false;plc.stopCPU();plc.loaded=false;$('phase').textContent=tasks[i].phase;$('tasktitle').textContent=tasks[i].id+' · '+tasks[i].title;$('taskGoal').textContent=Lab3Guide[tasks[i].id].goal;$('expectedEvidence').textContent='Evidence to keep: '+Lab3Guide[tasks[i].id].checkpoints;$('instructions').innerHTML=tasks[i].steps.map((t,n)=>'<li><div class="step-location">WHERE · '+esc(Lab3Guide[tasks[i].id].where[n])+'</div><p>'+esc(t)+'</p><p class="step-observe"><strong>Look for:</strong> '+esc(Lab3Guide[tasks[i].id].observe[n])+'</p></li>').join('');$('prediction').value=entry().prediction;$('explanation').value=entry().explanation;$('review').hidden=true;$('studio').hidden=false;document.querySelector('.answers').hidden=false;document.querySelector('.assignment').hidden=false;document.querySelector('.toolbar').hidden=false;document.querySelectorAll('#tasknav button').forEach((b,j)=>b.setAttribute('aria-current',String(i===j)));$('loadNote').textContent='Load this task’s workspace before testing. Captures are retained.';$('message').textContent='';records();render();}
function load(){workspaceTask=tasks[index].id;playing=false;acc=0;plc=new Lab3.PLC();ladderEditor.setSource(tasks[index].id==='I2'?Lab3.DEFAULT.replace('Auto AND StopOK AND NOT Trip','Auto AND NOT StopOK AND NOT Trip'):Lab3.DEFAULT,tasks[index].id==='P1');for(const k of ['held','stopInput','invalid','sourceFault'])$(k).checked=false;$('supply').value='1';$('outflow').value='.010';$('label').value='';$('message').textContent='Workspace loaded. Check and download the offline draft before RUN.';plc.loaded=false;render();}
function render(){const s=plc.snapshot(),dirty=$('code').value!==plc.program.source;$('status').textContent=s.cpu+' · '+s.state+' · '+s.t.toFixed(1)+' s · CPU revision '+s.revision+(dirty?' · draft differs':'');$('play').textContent=playing?'Pause process':'Play process';$('watch').innerHTML=[['Level_m','REAL / m',s.h.toFixed(3)],['SP_m','REAL / m',s.sp.toFixed(2)],['Flow_m3s','REAL / m³/s',s.q.toFixed(4)],['StopOK','BOOL',plc.stopOK],['LevelValid','BOOL',plc.valid],['SourceOK','BOOL',plc.source],['Auto','BOOL',s.state==='AUTO'],['Trip','BOOL',s.state==='TRIPPED'],['Bias_pct','REAL / %',plc.bias.toFixed(1)],['Output_pct','REAL / %',s.command.toFixed(2)],['Integral_J','REAL / %',s.J.toFixed(3)],['Flow_SP','REAL / m³/s',s.flowTarget.toFixed(4)],...LadderCore.MEMORY.map(k=>[k,'BOOL',plc.ladMemory.bits[k]]),...LadderCore.TIMERS.flatMap(k=>[[k+'.Q','BOOL',!!plc.ladMemory.timers[k]?.q],[k+'.ET','s',(plc.ladMemory.timers[k]?.et||0).toFixed(2)]])].map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('');$('networks').innerHTML=[['TripCause',plc.scan?.tripCause],['State = AUTO',s.state==='AUTO'],['PumpEnable',plc.scan?.permit],['Applied command > 0',s.command>0]].map(([label,value])=>'<div class="network '+(value?'on':'')+'">'+esc(label)+' : '+(value===undefined?'not evaluated':value?'TRUE':'FALSE')+'</div>').join('');$('scan').textContent=plc.scan?JSON.stringify(plc.scan,null,2):'No scan since initialization.';$('water').style.height=(s.h/2*100)+'%';$('levelLabel').textContent=s.h.toFixed(2)+' m';$('flowValues').innerHTML='Inlet '+s.q.toFixed(4)+' m³/s<br>Outlet '+s.qout.toFixed(4)+' m³/s<br>Command '+s.command.toFixed(1)+'%<br>Supply effectiveness '+Math.round(s.supply*100)+'%';$('events').textContent=plc.events.slice(-10).map(e=>e.t.toFixed(2)+' s · '+e.text).join('\n');plot();ladderEditor?.online(plc.scan,!dirty);}
function trendSVG(samples){const a=samples.slice(-6000),start=a[0]?.t||0,end=Math.max(start+1,a.at(-1)?.t||120),x=t=>55+(t-start)/(end-start)*970;let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 470" role="img" aria-label="Level, output and flow trends"><rect width="1100" height="470" fill="white"/>';for(const [title,y]of [['Level 0–2 m: blue PV / purple SP',22],['Pump command 0–100%: green',184],['Inlet flow 0–0.020 m³/s: orange / cascade target: purple',335]])svg+='<text x="55" y="'+y+'" font-size="18" fill="#203643">'+title+'</text>';for(const y of [42,145,204,290,355,430])svg+='<path d="M55 '+y+'H1025" stroke="#ccd7df"/>';for(const [key,color,y]of [['h','#177ab0',v=>145-v*51.5],['sp','#88529c',v=>145-v*51.5],['command','#187757',v=>290-v*.86],['q','#bf751a',v=>430-v/.02*75],['cascadeTarget','#88529c',v=>430-v/.02*75]]){const pts=a.filter(s=>Number.isFinite(s[key])).map(s=>x(s.t).toFixed(1)+','+y(s[key]).toFixed(1)).join(' ');svg+='<polyline fill="none" stroke="'+color+'" stroke-width="2" points="'+pts+'"/>';}return svg+'<text x="55" y="463" font-size="17">'+start.toFixed(1)+' s</text><text x="980" y="463" font-size="17">'+end.toFixed(1)+' s</text></svg>';}
function plot(){$('plot').innerHTML=trendSVG(plc.samples.filter(s=>s.t>=plc.t-120));}
function controlSettings(r){
 if(r.settings)return r.settings;
 try{const p=Lab3.compile(r.program);return {mode:p.mode,Kp:p.Kp,Ki:p.Ki,Kd:p.Kd,Ts:p.Ts,bias:null};}catch{return {};}
}
function comparison(list){
 if(!list.length)return '<p>No captures yet. Run the task and capture a checkpoint below.</p>';
 const num=(v,n=2)=>Number.isFinite(v)?v.toFixed(n):'—';
 return '<div class="comparison-wrap"><table class="comparison"><caption>Captured running conditions and results · error = SP − PV</caption><thead><tr>'+['Checkpoint','Mode / Kp / Ki / Kd','Bias / Ts','Time / supply','Error (m)','Peak (m)','At ≥99.9% output (s)'].map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+list.map(r=>{const c=controlSettings(r),m=r.metrics||{},v=r.snapshot;return '<tr>'+[esc(r.label)+(r.dirty?' <strong>(draft differs)</strong>':''),esc([c.mode,c.Kp,c.Ki,c.Kd].map(x=>x??'—').join(' / ')),num(c.bias)+'% / '+num(c.Ts)+' s',num(v.t,1)+' s / '+num(v.supply*100,0)+'%',num(m.finalError,4),num(m.peakLevel,4),num(m.saturatedSeconds,1)].map(x=>'<td>'+x+'</td>').join('')+'</tr>';}).join('')+'</tbody></table></div><p class="metric-note">Display curves retain bounded samples and extrema; JSON includes traceInfo. Peak and upper-limit time are calculated before reduction and cover the retained engine trace, not only the post-disturbance interval. Final error is a snapshot, not proof of steady state. Older captures without Bias metadata show —.</p>';
}
function records(){$('captures').innerHTML=comparison(entry().records);}

function capture(){if(!plc.loaded||!plc.scan)throw Error('Download the task program and execute a scan before capturing evidence.');if(entry().records.length>=12)throw Error('12 captures per task retained. Download before recording more.');const a=plc.samples;entry().records.push({version:Lab3.VERSION,settings:{mode:plc.program.mode,Kp:plc.program.Kp,Ki:plc.program.Ki,Kd:plc.program.Kd,Tf:plc.program.Tf,Ts:plc.program.Ts,bias:plc.bias},label:$('label').value.trim()||'Checkpoint '+(entry().records.length+1),at:new Date().toISOString(),program:plc.program.source,offlineDraft:$('code').value,dirty:$('code').value!==plc.program.source,prediction:entry().prediction,snapshot:plc.snapshot(),scan:plc.scan,metrics:{peakLevel:a.length?Math.max(...a.map(s=>s.h)):plc.h,finalError:plc.sp-plc.h,saturatedSeconds:a.filter(s=>s.command>=99.9).length*plc.program.Ts},events:plc.events.map(e=>({...e})),...Lab3Evidence.compact({samples:a})});records();persist();$('message').textContent='Capture saved with the running program and revision.';}
function evidence(){return {schema:1,version:Lab3.VERSION,student,exportedAt:new Date().toISOString(),tasks:tasks.map(t=>({...t,expectedEvidence:Lab3Guide[t.id].checkpoints,required:t.id!=='X1',...(work[t.id]||{prediction:'',explanation:'',records:[]})}))};}
function file(name,type,data){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function review(){playing=false;$('studio').hidden=true;document.querySelector('.answers').hidden=true;document.querySelector('.assignment').hidden=true;document.querySelector('.toolbar').hidden=true;$('review').hidden=false;$('summary').innerHTML=evidence().tasks.map(t=>'<div class="reviewRow"><strong>'+esc(t.id+' · '+t.title)+'</strong><p>'+t.records.length+' captures · '+(t.prediction.trim()?'prediction saved':'prediction missing')+' · '+(t.explanation.trim()?'explanation saved':'explanation missing')+(t.required?'':' · optional')+'</p><p>Evidence to check: '+esc(t.expectedEvidence)+'</p><p>'+((t.records.length<Lab3Guide[t.id].min)?'Not enough checkpoints for the suggested sequence.':'Checkpoint count reached; verify conditions and explanations yourself.')+'</p>'+comparison(t.records)+'</div>').join('');document.querySelectorAll('#tasknav button').forEach((b,i)=>b.setAttribute('aria-current',String(i===tasks.length)));}
function report(){const d=evidence();let h='<!doctype html><html lang="en"><meta charset="utf-8"><title>Lab 3 report</title><style>body{font:16px/1.55 Arial;color:#203643;background:#edf1f4}main{max-width:1100px;margin:auto;padding:32px;background:white}header,h2{background:#e9f2f6;border-left:5px solid #175e76;padding:16px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f6f8fa;border-left:3px solid #bd7914;padding:14px}h3{color:#175e76}table{border-collapse:collapse;width:100%;font-size:13px}caption{text-align:left;font-weight:bold;padding:10px;background:#e9f2f6}th,td{border:1px solid #ccd7df;padding:8px;text-align:left}th{background:#e7f1ed}tbody tr:nth-child(even){background:#f6f8fa}.metric-note{font-size:13px;color:#526572}@media print{body{background:white}section{break-before:page}h2,h3{break-after:avoid}}@page{size:A4 landscape;margin:14mm}</style><main><header><h1>EE4002 Lab 3</h1><p>'+esc(student)+'</p><p>'+esc(d.exportedAt)+'</p></header>';for(const t of d.tasks){h+='<section><h2>'+esc(t.id+' · '+t.title)+'</h2><p>'+esc(t.expectedEvidence)+'</p>'+comparison(t.records)+'<h3>Prediction and plan</h3><pre>'+esc(t.prediction)+'</pre>';for(const r of t.records)h+='<h3>'+esc(r.label)+'</h3><p>CPU revision '+r.snapshot.revision+(r.dirty?' · WARNING: draft differs from running program':'')+'</p>'+trendSVG(r.samples||[])+'<pre>'+esc(r.program)+'</pre><pre>'+esc(JSON.stringify({settings:controlSettings(r),snapshot:r.snapshot,scan:r.scan,metrics:r.metrics,events:r.events,traceInfo:r.traceInfo},null,2))+'</pre>';h+='<h3>Explanation</h3><pre>'+esc(t.explanation)+'</pre></section>';}h+='</main></html>';file('EE4002-Lab3-report.html','text/html',h);}
tasks.forEach((t,i)=>{const b=document.createElement('button');b.textContent=t.id;b.onclick=()=>select(i);$('tasknav').append(b);});const b=document.createElement('button');b.textContent='Review & Download';b.onclick=review;$('tasknav').append(b);
$('baseline').onclick=load;$('compile').onclick=()=>safe(()=>{Lab3.compile($('code').value);$('message').textContent='Program checks passed. Download in STOP to apply.';});$('download').onclick=()=>safe(()=>{if(workspaceTask!==tasks[index].id)throw Error('Load this task’s workspace before Download.');plc.download($('code').value);plc.loaded=true;$('message').textContent='Downloaded. CPU is STOP; select RUN, then press a fresh Start.';});$('run').onclick=()=>safe(()=>{if(!plc.loaded)throw Error('Download the task program first.');plc.runCPU();});$('stop').onclick=()=>{playing=false;plc.stopCPU();render();};$('step').onclick=()=>safe(()=>{if(!plc.loaded)throw Error('Download a program first.');playing=false;plc.step(true);render();});$('play').onclick=()=>safe(()=>{if(!plc.loaded)throw Error('Download a program first.');playing=!playing;});$('advance').onclick=()=>safe(()=>{if(!plc.loaded)throw Error('Download a program first.');playing=false;const n=Math.round(10/plc.program.Ts);for(let i=0;i<n;i++)plc.step();});
$('start').onclick=()=>{plc.start=true;plc.log('Start requested');render();};$('reset').onclick=()=>{plc.reset=true;plc.log('Reset requested');};for(const [id,key,invert]of [['held','held',false],['stopInput','stopOK',true],['invalid','valid',true],['sourceFault','source',true]])$(id).onchange=e=>{plc[key]=invert?!e.target.checked:e.target.checked;if(id==='held')plc.start=e.target.checked;plc.log(id+' = '+e.target.checked);render();};$('supply').onchange=e=>{plc.supply=Number(e.target.value);plc.log('Supply '+plc.supply);render();};$('applyLoad').onclick=()=>safe(()=>{const v=Number($('outflow').value);if(!Number.isFinite(v)||v<.004||v>.016)throw Error('Outlet must be 0.004–0.016 m³/s.');plc.qout=v;plc.log('Outlet '+v);});$('fixture').onclick=()=>safe(()=>{playing=false;const v=Number($('fixtureLevel').value);if(!Number.isFinite(v)||v<0||v>2)throw Error('Level must be 0–2 m.');plc.h=v;plc.log('Test fixture level '+v);});
for(const k of ['prediction','explanation'])$(k).oninput=e=>{entry()[k]=e.target.value;persist();};$('capture').onclick=()=>safe(capture);$('student').value=student;$('student').oninput=e=>{student=e.target.value;persist();};$('evidence').onclick=()=>file('EE4002-Lab3-evidence.json','application/json',JSON.stringify(evidence(),null,2));$('report').onclick=report;$('saveProject').onclick=()=>safe(()=>{Lab3.compile($('code').value);file('EE4002-Lab3-project.json','application/json',JSON.stringify({schema:1,version:Lab3.VERSION,source:$('code').value},null,2));});$('openProject').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>65000){$('message').textContent='Project file too large.';return;}try{const d=JSON.parse(await f.text());if(d.schema!==1)throw Error('Unsupported project schema.');Lab3.compile(d.source);playing=false;plc.stopCPU();ladderEditor.setSource(d.source);$('message').textContent='Project opened as an offline draft. Check and Download before running.';render();}catch(err){$('message').textContent=err.message;}};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>$(b.dataset.view).scrollIntoView({behavior:'smooth',block:'start'}));document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;render();}});

function logicWarmup(){
 const a=$('logicA').checked,b=$('logicB').checked,c=$('logicC').checked,left=$('logicGrouping').value!=='right';
 const contact=(name,on)=>'<span class="logic-contact '+(on?'powered':'')+'">─| '+name+' |─ '+(on?'TRUE':'FALSE')+'</span>';
 const parallel=(x,y)=>'<span class="logic-parallel"><span>'+x+'</span><span>'+y+'</span></span>';
 const result=left?(a&&b)||c:a&&(b||c);
 $('logicDrawing').innerHTML=(left?parallel(contact('A',a)+contact('B',b),contact('C',c)):contact('A',a)+parallel(contact('B',b),contact('C',c)))+'<strong class="logic-contact '+(result?'powered':'')+'">─( Output )─ '+result+'</strong>';
}
for(const id of ['logicA','logicB','logicC','logicGrouping'])$(id).onchange=logicWarmup;
logicWarmup();

let prev=performance.now(),lastPaint=0;function frame(now){const dt=Math.min(.1,(now-prev)/1000);prev=now;if(playing){acc+=dt*4;while(acc>=plc.program.Ts){plc.step();acc-=plc.program.Ts;}if(now-lastPaint>=100){render();lastPaint=now;}}requestAnimationFrame(frame);}ladderEditor=new LadderEditor(render);select(0);load();requestAnimationFrame(frame);
})();
