'use strict';
// Task-facing guidance only; the existing controller and assessment IDs are unchanged.
const Lab3Guide = {
 P1: {goal:'Build, deploy and verify a Boolean pump permission.',where:['Offline LAD editor → Network 2','PI / PID block → toolbar → Operator inputs','Online power flow → Watch table → Task evidence'],observe:['Series contacts must all pass. Try Delete and Undo without changing TripCause.','Predict using Bias + Kp × error + Ki × Ts × error; Download changes the CPU, editing alone does not.','Compare a healthy scan with a field-Stop scan. Explain the permission path, not just the tank motion.'],checkpoints:'Healthy first scan; field Stop scan. Include your command prediction and explanation.',min:2},
 P2: {goal:'Make a fair P/PI comparison and distinguish transient error from steady offset.',where:['PI / PID block → toolbar → Task evidence','Load task workspace → repeat the same sequence','Process & trends → capture comparison'],observe:['Studio uses fixed Bias = 50%, Kp = 50, SP = 1 m and Ts = 0.1 s. Label this capture “P at 120 s”.','Change only the mode. Label this capture “PI at 120 s”. Loading resets the plant; Download alone does not.','At nominal outlet and supply, 50% is the balance command: P can approach SP with zero error here. PI need not have the smaller error at 120 s. Inspect whether the trace is still moving.'],checkpoints:'P and PI at 120 s from identical initial conditions. Explain Bias and the observation-time limitation.',min:2},
 I1: {goal:'Choose and defend PI gains using a repeatable disturbance test.',where:['Prediction and test plan → PI / PID block','Toolbar clock → Watch table / Supply effectiveness','Task evidence → capture comparison'],observe:['Choose your own two sets. State a success criterion before running (for example, acceptable error and peak level); no universal best gains are assumed.','For each run: baseline supply until 60 s, then 65% supply until 120 s. Keep outlet, Bias, Ts and initial state unchanged.','Use both traces, peak level, final error and upper-limit time. If a trip occurs, capture it as a failed trial rather than silently resetting.'],checkpoints:'Two labelled PI trials at 120 s, with the supply change logged at 60 s; recommendation supported by evidence.',min:2},
 I2: {goal:'Diagnose a permission fault and verify safe restart behavior.',where:['Online power flow + Watch table','Offline contact Properties → toolbar → Operator inputs','Paused boundary-test fixture → Operator inputs'],observe:['Record the faulty behavior before editing; a successful Check does not establish correct logic.','Capture repaired healthy operation, pressed Stop, and released Stop with a fresh Start. Keep the generated running program as evidence.','Capture IDLE after Reset while Start remains held, then AUTO after release and a fresh Start. Explain why clearing a trip is not permission to restart.'],checkpoints:'Fault before repair; healthy repair; Stop; fresh restart; held-Start after Reset; release and new Start (six captures). TON is optional.',min:6},
 X1: {goal:'Explore cascade control after completing the four core tasks.',where:['PI / PID block','Watch table → Process & trends','Task evidence'],observe:['Use identical starting conditions. The outer output is a flow target.','Compare matched disturbance trials, not unrelated screenshots.','Discuss sensor cost, inner-loop response and actuator limits.'],checkpoints:'Optional: matched PI and CASCADE trials plus an explanation.',min:2}
};
