'use strict';
// Public assignments only. Answer keys and grading notes are not distributed here.
function installLabAssignments(taskData){Object.assign(taskData,{
 E:{title:'Independent 1 · A new known input',goal:'Measure TK-201 at 0.75 m, gain 1, CH0 and 20 SPS. Use the nominal 3.3 V reference.',steps:['Before measuring, record your predicted current, shunt voltage and raw ADC code.','Set the input and configuration yourself. Verify acceptance, then obtain a settled reading.','Save a checkpoint labeled I1. Explain any difference between physical and reconstructed level.'],pass:'Your prediction, accepted configuration, settled checkpoint and explanation.',target:'bench'},
 F:{title:'Independent 2 · Diagnose an unusable reading',goal:'At 1.50 m, investigate gain 2. Then choose a usable gain and repeat the measurement.',steps:['Predict whether the amplified input fits the converter range. Explain your reasoning before sampling.','Configure and test gain 2. Record the raw output and status in Notes.','Choose a suitable gain. Verify its acceptance, repeat the test and save I2-recovery. Explain why the new reading is usable.'],pass:'Before/after observations, your chosen correction and a recovery checkpoint.',target:'registers'},
 G:{title:'Independent 3 · DAC feedback',goal:'Generate a DAC output using code 1024 and verify it using the ADC.',steps:['Record the predicted output voltage and feedback code before measuring.','Select the appropriate ADC channel and gain. Configure, read back and obtain settled data.','Save I3. Explain what register read-back proves and what ADC feedback adds.'],pass:'One CH2 checkpoint and a distinction between acceptance and feedback.',target:'registers'},
 H:{title:'Independent 4 · Configuration failure',goal:'Establish CH0 operation, then investigate a CH1 request that does not take effect.',steps:['Start with nominal CH0. Select Configuration writes disappear. Request CH1 at gain 1 and 20 SPS.','Choose a check that tells whether your request took effect. Record intended and observed state, without deleting the failed transaction.','Remove the fault, correct the configuration and repeat the test. Save I4-recovery. Identify the evidence for successful recovery.'],pass:'Failed transaction, diagnostic reasoning and a verified recovery checkpoint.',target:'registers'}
});
taskData.Submit.steps=['Complete the four independent assignments I1–I4. Keep practice records labeled separately.','Include predictions, configuration read-backs, failure observations and recovery reasoning.','Complete two asset rows and one data-flow row. State one limitation of the simulation.','Export one JSON file and check your names and records. The instructor evaluates your reasoning; record counts are not grades.'];
taskData.Submit.pass='Four independent checkpoints, predictions and explanations, two assets and one flow.';
}
