'use strict';
// Presentation layer only: all conversions and register transactions use Workbench.
if(!isTour){
const visual=document.createElement('section');visual.id='liveBench';
visual.innerHTML=`<div class="live-heading"><div><span class="eyebrow">LIVE SIGNAL CHAIN</span><h2>One input. Every stage visible.</h2></div><span id="liveClock">Paused</span></div>
<div class="live-layout"><div class="tank-panel"><div class="tank-scale"><span>2.00 m</span><span>1.00 m</span><span>0.00 m</span></div><div id="tankTouch" class="tank-vessel" aria-hidden="true"><div id="tankWater"></div><div id="reportedLine"></div><strong id="tankNumber">1.00 m</strong></div><label class="tank-input">Physical level <output id="vLevelText"></output><input id="vLevel" type="range" min="0" max="2" step="0.05" value="1" aria-label="Physical tank level in metres"></label><p class="visual-small">Drag the level. Dashed line: last CH0 estimate, when available.</p></div>
<div class="signal-panel"><div class="signal-stages"><div><span>TRANSMITTER</span><strong id="vCurrent"></strong><small>4 + 8h mA</small></div><div><span>150 Ω SHUNT</span><strong id="vShunt"></strong><small>V = I × R</small></div><div><span>MUX / PGA</span><strong id="vInput"></strong><small id="vRange"></small></div><div><span>ADC DATA</span><strong id="vCode"></strong><small id="vEstimate"></small></div></div>
<div class="visual-fields"><label>Proposed channel<select id="vMux"><option value="0">CH0 · tank</option><option value="1">CH1 · test source</option><option value="2">CH2 · DAC loopback</option><option value="3">CH3 · ground</option></select></label><label>Proposed gain<select id="vGain"><option value="0">×1</option><option value="1">×2</option><option value="2">×4</option><option value="3">×8</option></select></label><label>Proposed rate<select id="vRate"><option value="0">5 SPS</option><option value="1">20 SPS</option><option value="2">100 SPS</option><option value="3">1000 SPS</option></select></label></div>
<div class="toolbar"><button id="vWrite">Write proposed CONFIG</button><button id="vRead">Read CONFIG</button><button id="vStep" class="primary">Sample + read</button><button id="vPlay">Play slowly</button></div><p id="liveMeaning" role="status"></p><p class="visual-small">Play shows two conversions per wall-clock second. CONFIG rate sets simulation time; this is slowed playback, not real-time acquisition. Pause before saving evidence.</p></div></div>
<div class="register-strip"><div><h3>Proposed CONFIG <span id="vProposed"></span></h3><div id="proposedBits" class="bits"></div></div><div><h3>IC CONFIG <span id="vAccepted"></span></h3><div id="acceptedBits" class="bits"></div></div><div><h3>STATUS now <span id="vStatus"></span></h3><div id="statusBits" class="bits"></div></div></div><p class="visual-small">CONFIG: EN · reserved · GAIN[1:0] · MUX[1:0] · RATE[1:0]. IC state is simulator instrumentation; use Read CONFIG as transaction evidence. DATA: <code id="dataBits"></code></p>
<details id="signalHistory" open><summary>Linked signal history <span class="visual-small">shared simulation time</span></summary><canvas id="signalChart" height="330" role="img" aria-label="Physical level, transmitter current and ADC code on a shared time axis"></canvas><p class="visual-small">Input snapshots at conversion times, not an oscilloscope capture. Orange ADC points are transient. Channel/gain changes break the code trace. Dragging while paused changes the live input, not historical samples.</p></details>`;
document.querySelector('main').prepend(visual);
const guideLink=document.createElement('a');guideLink.href='#guided';guideLink.textContent='Task steps ↓';guideLink.className='visual-guide-link';visual.querySelector('.live-heading').append(guideLink);
let timer=null;
const faultLabel=document.createElement('label');faultLabel.textContent='Fault injection';const faultSelect=$('fault').cloneNode(true);faultSelect.id='vFault';faultLabel.append(faultSelect);visual.querySelector('.visual-fields').append(faultLabel);
const set=(id,text)=>$(id).textContent=text;
function stop(){clearInterval(timer);timer=null;set('vPlay','Play slowly');set('liveClock','Paused');}
function sample(){if(!lab.enabled){message('Enable the ADC: prepare Task A, or set Enable to 1 below, then write CONFIG.');stop();render();update();return;}lab.step();lab.read(2);lab.read(3);lab.read(4);message('One conversion recorded and read. DRDY cleared by DATA_L read.');render();update();}
function changeLevel(value){$('level').value=String(Math.max(0,Math.min(2,Math.round(value*20)/20)));$('level').dispatchEvent(new Event('input',{bubbles:true}));}
$('vLevel').oninput=()=>changeLevel(+$('vLevel').value);
$('tankTouch').onpointerdown=e=>{e.preventDefault();$('tankTouch').setPointerCapture(e.pointerId);const move=ev=>{const r=$('tankTouch').getBoundingClientRect();changeLevel(2*(1-(ev.clientY-r.top)/r.height));};move(e);$('tankTouch').onpointermove=move;};
$('tankTouch').onpointerup=$('tankTouch').onpointercancel=()=>{$('tankTouch').onpointermove=null;};
for(const [proxy,source]of [['vMux','mux'],['vGain','gain'],['vRate','rate'],['vFault','fault']])$(proxy).onchange=()=>{$(source).value=$(proxy).value;$(source).dispatchEvent(new Event('change',{bubbles:true}));};
$('vWrite').onclick=()=>{$('copy').click();$('write').click();};$('vRead').onclick=()=>$('configRead').click();$('vStep').onclick=()=>{stop();sample();};$('vPlay').onclick=()=>{if(timer){stop();return;}if(!lab.enabled){sample();return;}set('vPlay','Pause');set('liveClock','Slow playback');timer=setInterval(sample,500);};
// Keep checkpoints deterministic and stop unattended playback on navigation.
for(const id of ['save','export','csv','reset','newSession','watchTour','prepare','write','dacWrite','step','three'])$(id).addEventListener('click',stop,true);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='ee4002-lab-hidden')stop();});
function bits(id,value,kind){const host=$(id);if(!host.children.length)for(let i=7;i>=0;i--){const b=document.createElement('span');b.className='bit';b.dataset.bit=i;host.append(b);}for(const b of host.children){const i=+b.dataset.bit,v=(value>>i)&1,old=b.dataset.value;b.dataset.value=v;b.classList.toggle('on',!!v);b.classList.toggle('changed',old!==undefined&&old!==String(v));b.textContent=i+': '+v;b.title=kind==='status'?['DRDY','OVERRANGE','SETTLING','REF_ERROR (reserved)','SPI_ERROR','OVERRUN','reserved','reserved'][i]:['RATE0','RATE1','MUX0','MUX1','GAIN0','GAIN1','reserved','EN'][i];}}
function paintSignals(){
set('vLevelText',lab.level.toFixed(2)+' m');$('vLevel').value=lab.level;set('tankNumber',lab.level.toFixed(2)+' m');$('tankWater').style.height=lab.level/2*100+'%';
set('vCurrent',lab.current.toFixed(2)+' mA');set('vShunt',(lab.current*.15).toFixed(3)+' V');set('vInput','CH'+lab.channel+' · ×'+lab.gain);set('vRange',(lab.inputVoltage*lab.gain).toFixed(3)+' V / '+lab.ref.toFixed(1)+' V limit');set('vCode',lab.sampleTime===null?'No sample':lab.code+' / '+hex(lab.code,3));
const s=lab.samples.at(-1),estimate=s&&s.channel===0?s.tag_level_m:null;$('reportedLine').hidden=estimate===null||lab.sampleTime===null;$('reportedLine').style.bottom=Math.max(0,Math.min(100,(estimate||0)/2*100))+'%';
set('vEstimate',s&&lab.sampleTime!==null?'Last conversion: '+s.sim_time_ms+' ms':'Write CONFIG, then sample');
for(const [proxy,source]of [['vMux','mux'],['vGain','gain'],['vRate','rate'],['vFault','fault']])$(proxy).value=$(source).value;
set('vProposed',hex(encoded()));set('vAccepted',hex(lab.config));set('vStatus',hex(lab.status));bits('proposedBits',encoded());bits('acceptedBits',lab.config);bits('statusBits',lab.status,'status');set('dataBits',lab.code.toString(2).padStart(12,'0').replace(/(.{4})(?=.)/g,'$1 ')+' (12 bits)');
const pending=!s||lab.sampleTime===null||s.config!==hex(lab.config)||s.physical_level_m!==lab.level||s.fault!==lab.fault||s.assumed_reference_V!==lab.assumedRef||s.input_voltage_V!==+lab.inputVoltage.toFixed(6);
let explanation=!lab.enabled?'ADC stopped. Proposed settings have not enabled the IC.':pending?'Input or configuration changed. ADC DATA still holds the previous conversion.':s&&!s.settled?'Transient output: SETTLING was set at conversion.':s&&(parseInt(s.status,16)&2)?'Saturated output: OVERRANGE was set. A numerical result is not a valid measurement.':'Latest conversion is settled. Check reference, channel and fault state before trusting it.';
if(lab.fault==='freeze')explanation+=' Frozen transmitter: tank motion no longer changes the current.';
if(encoded()!==lab.config)explanation+=' Proposed CONFIG differs from IC state.';
set('liveMeaning',explanation);visual.classList.toggle('signal-alert',lab.fault!=='none'||!!(lab.live&2));
drawSignals();
}
function drawSignals(){const cv=$('signalChart'),w=cv.clientWidth;if(w<50)return;const h=330,dpr=devicePixelRatio||1;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d');c.scale(dpr,dpr);const css=getComputedStyle(visual),ink=css.color,grid=css.getPropertyValue('--visual-line')||'#cbd5df';c.font='13px Arial';const ss=lab.samples.slice(-60),l=58,r=w-18,min=ss[0]?.sim_time_ms||0,max=Math.max(min+1,ss.at(-1)?.sim_time_ms||1);const lanes=[{key:'physical_level_m',max:2,name:'Level (m)',color:'#b85a20'},{key:'source_current_mA',max:20,name:'Current (mA)',color:'#087c83'},{key:'raw_code',max:4095,name:'ADC code',color:'#286faf'}];
lanes.forEach((a,k)=>{const top=25+k*96,bottom=top+65;c.fillStyle=ink;c.fillText(a.name,l,top-8);c.fillText(String(a.max),5,top+5);c.fillText('0',28,bottom+3);c.strokeStyle=grid;c.beginPath();c.moveTo(l,top);c.lineTo(r,top);c.moveTo(l,bottom);c.lineTo(r,bottom);c.stroke();let prev=null;c.strokeStyle=a.color;c.lineWidth=2;for(const s of ss){const val=s[a.key];if(!Number.isFinite(val)){prev=null;continue;}const x=l+(s.sim_time_ms-min)/(max-min)*(r-l),y=bottom-val/a.max*(bottom-top);if(prev&&(k!==2||prev.s.config===s.config)){c.beginPath();c.moveTo(prev.x,prev.y);c.lineTo(x,y);c.stroke();}c.fillStyle=k===2&&!s.settled?'#b85a20':a.color;c.beginPath();c.arc(x,y,3,0,Math.PI*2);c.fill();prev={x,y,s};}});
c.fillStyle=ink;c.fillText(Math.round(min)+' ms',l,318);c.textAlign='right';c.fillText(Math.round(max)+' ms',r,318);c.textAlign='left';if(!ss.length)c.fillText('Sample to begin the history',l,152);
}
const originalRender=render;render=function(){originalRender();paintSignals();};new ResizeObserver(drawSignals).observe($('signalChart'));paintSignals();
}
