/* Zero-dependency build. All paths are relative to this website, not the course workspace. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const lab=path.resolve(__dirname,'../lab1');
// These fragments share one private lexical scope; hooks register before initialization.
const order=['core','guide','visual','lesson','steps','host','report_ui'];
const content='/* Generated by scripts/build-lab1.cjs from lab1/src; edit the sources, then rebuild. */\n(function(){\n\'use strict\';\n'+order.map(n=>'\n// ---- '+n+' ----\n'+fs.readFileSync(path.join(lab,'src',n+'.js'),'utf8')).join('\n')+'\nready=true;showTask(activeTask);render();\n})();\n';
new vm.Script(content);
const target=path.join(lab,'runtime.js');
if(process.argv.includes('--check')){
 if(fs.readFileSync(target,'utf8')!==content)throw Error('runtime.js is stale. Run node scripts/build-lab1.cjs');
 console.log('PASS: runtime matches the included sources.');
}else {fs.writeFileSync(target,content);console.log('Built lab1/runtime.js');}
