'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let task=0,latest=null,trial=null,cursor=0,timer=null,mode='serial',learning=null;
let saved={schema:1,student:'',work:{}};const storageKey='ee4002-lab4-v1';
try{const s=JSON.parse(localStorage.getItem(storageKey));if(s&&(s.schema===undefined||s.schema===1)&&typeof s.work==='object'&&s.work){saved.student=String(s.student||'').slice(0,200);for(const t of Lab4Tasks){const w=s.work[t.id];if(w&&typeof w==='object')saved.work[t.id]={prediction:String(w.prediction||''),explanation:String(w.explanation||''),captures:Array.isArray(w.captures)?w.captures.filter(c=>c&&['serial','modbus','integrity','tcp'].includes(c.kind)&&c.data).slice(-12):[]};}}}catch(e){}
function work(){const id=Lab4Tasks[task].id;return saved.work[id]||(saved.work[id]={prediction:'',explanation:'',captures:[]});}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(saved));$('storageStatus').textContent='Saved in this browser. Download all tasks at the end.';}catch(e){$('storageStatus').textContent='Browser storage unavailable. Keep this page open and download your evidence.';}}
function notice(s){$('notice').textContent=s;}
for(const side of ['tx','rx'])$(''+side+'Config').innerHTML=`<label>Baud<select id="${side}Baud">${Lab4.BAUDS.map(b=>`<option>${b}</option>`).join('')}</select></label><label>Parity<select id="${side}Parity"><option value="N">None</option><option value="E">Even</option><option value="O">Odd</option></select></label><label>Stop bits<select id="${side}Stop"><option>1</option><option>2</option></select></label>`;
function cfg(s){return {baud:+$(s+'Baud').value,parity:$(s+'Parity').value,stop:+$(s+'Stop').value};}
function stop(){clearInterval(timer);timer=null;$('animate').textContent='Animate';}
function view(v){mode=v;$('serialPane').hidden=v!=='serial';$('modbusPane').hidden=v!=='modbus';for(const m of ['serial','modbus'])$(m+'View').setAttribute('aria-pressed',m===v);}
function invalidate(){learning?.clear();latest=null;$('capture').disabled=true;notice('Settings changed. Send or read again before capturing.');linkSummary();}
function linkSummary(){const a=cfg('tx'),b=cfg('rx');$('linkSettings').textContent=`RTU client: ${a.baud} 8${a.parity}${a.stop}; server: ${b.baud} 8${b.parity}${b.stop}. Wire condition: ${$('fault').value}. Change these in Serial Sender / Receiver. TCP ignores UART settings and the serial wire condition.`;}
function load(){learning?.reset();stop();for(const s of ['tx','rx']){ $(s+'Baud').value='9600';$(s+'Parity').value='E';$(s+'Stop').value='1';}for(const [id,v]of Object.entries({format:'hex',payload:'03',fault:'none',transport:'rtu',unit:1,fc:3,address:0,quantity:1,scale:.001,level:750}))$(id).value=v;
 if(task===2){$('rxBaud').value='19200';$('payload').value='41';}if(task===3){$('address').value=3;$('scale').value=.01;}
 latest=null;trial=null;cursor=0;$('capture').disabled=true;$('wave').innerHTML='Send a trial to generate the waveform.';$('receive').textContent='Ready for a new trial.';$('serialDetails').innerHTML='';$('transactionResult').textContent='Ready for a new transaction.';$('requestBytes').textContent='—';$('responseBytes').textContent='—';$('decode').innerHTML='';$('inspectWave').disabled=true;view(Lab4Tasks[task].mode);linkSummary();notice('Task setup loaded. Existing captures and answers are kept.');}
function select(i){stop();task=i;const review=i===Lab4Tasks.length;$('assignment').hidden=review;$('workbench').hidden=review;$('review').hidden=!review;document.querySelectorAll('#tasknav button').forEach((b,j)=>b.setAttribute('aria-current',i===j));if(review){renderReview();return;}const t=Lab4Tasks[i];for(const id of ['framing','tcpLesson','integrity','crcLink'])$(id).hidden=t.id!=='P2';$('phase').textContent=t.phase;$('tasktitle').textContent=t.id+' · '+t.title;$('steps').innerHTML=t.steps.map(([h,p])=>`<li><strong>${esc(h)}</strong><p>${esc(p)}</p></li>`).join('');$('expectation').textContent='Keep: '+t.evidence;const w=work();$('prediction').value=w.prediction;$('explanation').value=w.explanation;$('label').value='';load();renderCaptures();}
$('tasknav').innerHTML=[...Lab4Tasks.map(t=>t.id+' · '+t.title),'Review & Download'].map((t,i)=>`<button data-task="${i}">${esc(t)}</button>`).join('');$('tasknav').onclick=e=>{const b=e.target.closest('[data-task]');if(b)select(+b.dataset.task);};
function wave(){if(!trial)return;const n=$('zoom').value==='all'?trial.wire.length:Math.min(trial.wire.length,trial.signal.charBits+2),x=t=>45+t*900/n,y=b=>b===1?45:105;let path=`M 45 ${y(trial.wire[0])}`;for(let i=0;i<n;i++)path+=` H ${x(i+1)}${i+1<n?' V '+y(trial.wire[i+1]):''}`;const dots=trial.frames.flatMap(f=>f.samples).filter(s=>s.t*trial.tx.baud<=n).map(s=>`<circle cx="${x(s.t*trial.tx.baud)}" cy="${s.bit===null?130:y(s.bit)}" r="4" fill="${s.label.startsWith('d')?'#168365':'#bf7614'}"><title>${esc(s.label)}: ${s.bit}</title></circle>`).join('');
 $('wave').innerHTML=`<svg viewBox="0 0 1000 175" role="img" aria-label="UART line and receiver sampling points"><text x="6" y="48">1</text><text x="6" y="108">0</text><path d="${path}" fill="none" stroke="#176d78" stroke-width="3"/>${dots}${n<30?trial.signal.labels.slice(0,n).map((s,i)=>`<text x="${x(i+.5)}" y="145" text-anchor="middle">${esc(s)}</text>`).join(''):''}<line x1="${x(Math.min(cursor,n))}" x2="${x(Math.min(cursor,n))}" y1="20" y2="120" stroke="#b14433" stroke-width="2"/><text x="45" y="170">Displayed duration: ${(n/trial.tx.baud*1000).toFixed(3)} ms · TX bit time ${(1000/trial.tx.baud).toFixed(4)} ms</text></svg>`;$('cursorInfo').textContent=`Bit ${cursor} · ${(cursor/trial.tx.baud*1000).toFixed(3)} ms`;
}
function showSerial(r){trial=r;cursor=0;stop();$('receive').className='result'+(r.equal?'':' bad');$('receive').textContent=`Sent: ${Lab4.hex(r.sent)} | Accepted RX: ${Lab4.hex(r.received)||'none'}. ${r.equal?'Bytes match.':'Bytes do not match.'} ${r.configMatch?'Endpoint settings match.':'Endpoint settings differ; matching bytes alone do not prove compatibility.'}`;$('serialDetails').innerHTML=`<p>One TX character: ${r.signal.charBits} bits / ${r.tx.baud} = ${r.charMs.toFixed(3)} ms. Invalid frames are not accepted as received bytes.</p><div class="table-wrap"><table><tr><th>Frame</th><th>Decoded byte</th><th>Parity</th><th>Stop / complete</th><th>Accepted</th></tr>${r.frames.map((f,i)=>`<tr><td>${i+1}</td><td>${Lab4.hex([f.byte])}</td><td>${r.rx.parity==='N'?'Not checked':f.parityOK?'OK':'Error'}</td><td>${f.framingOK&&f.complete?'OK':'Error'}</td><td>${f.ok?'Yes':'No'}</td></tr>`).join('')}</table></div>`;wave();}
$('send').onclick=()=>{try{const r=Lab4.serial(Lab4.parse($('payload').value,$('format').value),cfg('tx'),cfg('rx'),$('fault').value);showSerial(r);latest={kind:'serial',data:r};$('capture').disabled=false;notice('Trial complete. Compare your prediction, then capture the result.');}catch(e){invalidate();notice(e.message);}};
$('read').onclick=()=>{try{const c={transport:$('transport').value,unit:+$('unit').value,fc:+$('fc').value,address:+$('address').value,quantity:+$('quantity').value,scale:+$('scale').value,level:+$('level').value,fault:$('fault').value},r=Lab4.transaction(c,cfg('tx'),cfg('rx'));latest={kind:'modbus',data:r};$('capture').disabled=false;$('requestBytes').textContent=Lab4.hex(r.request);$('responseBytes').textContent=Lab4.hex(r.response)||'No response';$('transactionResult').className='result'+(r.outcome==='normal'?'':' bad');$('transactionResult').textContent=r.reason||(r.exception?'Exception '+r.exception+(r.exception===2?' · Illegal data address':' · Illegal function'):`Normal response. Raw registers: ${r.raw.join(', ')}.${r.display===null?'':' Client display: '+r.display.toFixed(3)+' m.'}`);$('decode').innerHTML=`<p>Unit ${c.unit} · FC ${c.fc} · PDU address ${c.address} · quantity ${c.quantity}.</p><p>${c.transport==='rtu'?'RTU: unit + function/data + CRC (low byte first).':'TCP: transaction ID 42, protocol ID 0, length counts Unit ID + PDU. No RTU CRC.'}</p><p>${r.outcome==='normal'?'Data bytes: '+Lab4.hex(r.raw.flatMap(n=>[n>>8,n&255]))+'; each register is high byte first.':'Distinguish a protocol exception from a missing or undecodable response.'}</p>`;$('inspectWave').disabled=!r.link;learning?.show(r);notice('Transaction complete. Capture before changing settings.');}catch(e){invalidate();notice(e.message);}};
$('inspectWave').onclick=()=>{if(latest?.kind==='modbus'&&latest.data.link){showSerial(latest.data.link);view('serial');notice('Showing the last Modbus request waveform. Send starts a separate serial trial; capture still records the Modbus transaction.');}};
$('animate').onclick=()=>{if(!trial)return;if(timer){stop();return;}const end=$('zoom').value==='all'?trial.wire.length:Math.min(trial.wire.length,trial.signal.charBits+2);if(cursor>=end)cursor=0;$('animate').textContent='Pause';timer=setInterval(()=>{cursor++;wave();if(cursor>=end)stop();},300);};$('nextBit').onclick=()=>{stop();if(trial){cursor=Math.min(cursor+1,trial.wire.length);wave();}};$('replay').onclick=()=>{stop();cursor=0;wave();};$('zoom').onchange=()=>{stop();cursor=0;wave();};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
function describe(c){const d=c.data;if(c.kind==='tcp')return `TCP walkthrough · complete response, raw ${d.raw} · ACK answer: ${d.ackAnswer}`;if(c.kind==='integrity')return `Integrity · TX ${Lab4.hex(d.sent)} → RX ${Lab4.hex(d.received)} · parity ${d.parityOK?'match':'mismatch'} · sum ${d.sumOK?'match':'mismatch'} · CRC ${d.crcOK?'match':'mismatch'} (TX 0x${d.txCRC.toString(16).padStart(4,'0')}, RX 0x${d.rxCRC.toString(16).padStart(4,'0')})`;return c.kind==='serial'?`TX ${Lab4.hex(d.sent)} → RX ${Lab4.hex(d.received)||'none'} · ${d.equal?'match':'mismatch'}`:`${d.config.transport.toUpperCase()} · address ${d.config.address} · ${d.outcome} · raw ${d.raw.join(', ')||'—'} · display ${d.display===null?'—':d.display+' m'}`;}
function renderCaptures(){$('captures').innerHTML=work().captures.map((c,i)=>`<div class="capture"><strong>${esc(c.label)}</strong><p>${esc(describe(c))}</p><button data-remove="${i}">Remove capture</button></div>`).join('');}
$('captures').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){work().captures.splice(+b.dataset.remove,1);persist();renderCaptures();}};
$('capture').onclick=()=>{if(!latest)return notice('Send or read a new trial first.');if(work().captures.length>=12)return notice('Maximum 12 captures per task. Remove an unnecessary capture first.');const label=$('label').value.trim();if(!label)return notice('Give this checkpoint a label before capturing.');work().captures.push(JSON.parse(JSON.stringify({...latest,label,at:new Date().toISOString(),prediction:work().prediction})));persist();renderCaptures();notice('Captured. Continue the task; download all results from Review & Download.');};
for(const id of ['prediction','explanation'])$(id).oninput=()=>{work()[id]=$(id).value;persist();};$('student').value=saved.student;$('student').oninput=()=>{saved.student=$('student').value;persist();};
function renderReview(){$('summary').innerHTML=Lab4Tasks.map(t=>{const w=saved.work[t.id]||{captures:[]};return `<div class="capture"><h3>${esc(t.id+' · '+t.title)}</h3><p>${w.captures.length} capture(s); expected at least ${t.min}. ${w.prediction?.trim()?'Prediction recorded.':'Prediction missing.'} ${w.explanation?.trim()?'Explanation recorded.':'Explanation missing.'}</p><p>${esc(t.evidence)}</p><ul>${Lab4.evidenceChecks(t.id,w.captures).map(([label,ok])=>`<li>${ok?'Recorded':'Missing / check'}: ${esc(label)}</li>`).join('')}</ul></div>`;}).join('')+'<p>Counts are a completeness reminder, not an automatic grade. Check that each required comparison is actually present.</p>';notice('Review your evidence before downloading.');}
function evidence(){return {schema:1,lab:'EE4002 Lab 4',version:Lab4.VERSION,exported:new Date().toISOString(),student:saved.student,tasks:Lab4Tasks.map(t=>({id:t.id,title:t.title,expected:t.evidence,...(saved.work[t.id]||{prediction:'',explanation:'',captures:[]})}))};}
function reportSelfCheck(e){
 const checks=[['Name / student ID',Boolean(e.student?.trim())]];
 for(const t of e.tasks){const spec=Lab4Tasks.find(s=>s.id===t.id);
  checks.push([t.id+' · Prediction / diagnosis',Boolean(t.prediction?.trim())],[t.id+' · Explanation / comparison',Boolean(t.explanation?.trim())],[t.id+' · Captures: '+t.captures.length+' / '+spec.min+' minimum',t.captures.length>=spec.min],...Lab4.evidenceChecks(t.id,t.captures).map(([label,ok])=>[t.id+' · '+label,ok]));
 }
 const missing=checks.filter(([,ok])=>!ok).length;
 return '<aside class="evidence-review" style="margin:24px 0;padding:20px;background:'+(missing?'#fff4df':'#e6f3ed')+';border-left:5px solid '+(missing?'#b87517':'#287755')+'"><h2>Evidence self-check</h2><p>'+(missing?'Missing / check items: '+missing+'. See the checklist below.':'Required saved items and evidence checkpoints are present.')+'</p><ul>'+checks.map(([label,ok])=>'<li><strong>'+(ok?'Recorded':'Missing / check')+':</strong> '+esc(label)+'</li>').join('')+'</ul><p>This is an evidence checklist, not an automatic grade. It checks saved writing and the task evidence conditions used in Review. An ACK answer is recorded regardless of the selected option; written reasoning still requires instructor review. No files have been submitted.</p></aside>';
}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('json').onclick=()=>download('EE4002-Lab4-evidence.json',JSON.stringify(evidence(),null,2),'application/json');
$('report').onclick=()=>{const e=evidence();download('EE4002-Lab4-report.html',`<!doctype html><html lang="en"><meta charset="utf-8"><title>Lab 4 report</title><style>body{font:18px/1.5 Calibri,Arial;max-width:1000px;margin:40px auto;padding:20px;color:#203643}header{background:#173f50;color:white;padding:25px}section{border-top:5px solid #176d78;margin:30px 0;padding:20px;background:#f2f7f8}article{border-left:4px solid #bf7614;background:#fff8eb;padding:12px;margin:15px 0;break-inside:avoid}pre{white-space:pre-wrap;overflow-wrap:anywhere}p{white-space:pre-wrap}@media print{*{print-color-adjust:exact;-webkit-print-color-adjust:exact}body{margin:0}}</style><header><h1>Lab 4 · Serial & Modbus</h1><p>${esc(e.student||'Name not entered')} · Version ${esc(e.version)}</p></header>${reportSelfCheck(e)}${e.tasks.map(t=>`<section><h2>${esc(t.id+' · '+t.title)}</h2><p>Expected: ${esc(t.expected)}</p><h3>Prediction / diagnosis</h3><p>${esc(t.prediction||'Not recorded')}</p>${t.captures.map(c=>`<article><h3>${esc(c.label)}</h3><p>${esc(c.at)}<br>${esc(describe(c))}</p><p>Prediction at capture: ${esc(c.prediction)}</p><pre>${esc(['integrity','tcp'].includes(c.kind)?JSON.stringify(c.data,null,2):c.kind==='serial'?'TX '+JSON.stringify(c.data.tx)+'\nRX '+JSON.stringify(c.data.rx)+'\nWire condition: '+c.data.fault:'Request: '+Lab4.hex(c.data.request)+'\nResponse: '+Lab4.hex(c.data.response)+'\nConfiguration: '+JSON.stringify(c.data.config))}</pre></article>`).join('')}<h3>Explanation and comparison</h3><p>${esc(t.explanation||'Not recorded')}</p></section>`).join('')}</html>`,'text/html');};
for(const id of ['txBaud','txParity','txStop','rxBaud','rxParity','rxStop','format','payload','fault','transport','unit','fc','address','quantity','scale','level'])$(id).addEventListener('input',invalidate);
$('load').onclick=load;$('serialView').onclick=()=>view('serial');$('modbusView').onclick=()=>view('modbus');select(0);

learning=Lab4Learning.init({get:$,model:Lab4,setLatest:value=>{latest=value;},notice});
Lab4Integrity.init({get:$,model:Lab4,setLatest:value=>{latest=value;},notice});
