'use strict';
window.TimingTasks={
5:{title:'Lab 5 · Network delivery and recovery',subtitle:'Lecture 9 · CAN arbitration, queueing and freshness',tasks:[
 {id:'P1',title:'CAN bus access',phase:'Practice · 10 min',setup:{mode:'can',rate:500,bg:4,id:384,period:10,base:0,outage:0,deadline:1},steps:['Predict: at 500 kbit/s, how long does an assumed 130-bit frame occupy the bus? Compare sensor ID 384 (0x180) with background ID 512 (0x200).','Run the baseline. Inspect the first-cycle transmission table: lower CAN IDs win among ready frames. Capture it.','Change the sensor ID to 768 (0x300), rerun and capture. Explain the different waiting time.'],min:2,compare:'id',prompt:'Explain the first differing identifier bit and why arbitration delays the losing node. What does this model omit?'},
 {id:'P2',title:'Ethernet queueing',phase:'Practice · 12 min',setup:{mode:'ethernet',rate:100,bg:8,id:384,period:10,base:2,outage:0,deadline:2.5,qos:false},steps:['Predict: a background frame occupies 12,000/100,000,000 seconds. Eight such frames precede a 1,200-bit sensor frame in FIFO. Add 2 ms downstream delay.','Run FIFO and capture. Inspect maximum delivery delay and deadline misses.','Enable priority queueing, leaving everything else unchanged. Run and capture. Compare delays.'],min:2,compare:'qos',prompt:'What improved? Why do QoS and a high bitrate still fail to establish a universal end-to-end deadline?'},
 {id:'I1',title:'Meet a delivery deadline',phase:'Independent · 13 min',setup:{mode:'ethernet',rate:10,bg:12,id:384,period:10,base:2,outage:0,deadline:5,qos:false},steps:['Run and capture the supplied overloaded baseline before editing. Identify the source of waiting.','Keep the 5 ms deadline, 10 ms period, 12 background frames and 2 ms downstream delay. Choose a bitrate and/or queue policy that meets the deadline.','Capture the revised run. Support your design using serialization and waiting-time calculations.'],min:2,compare:'design',prompt:'Defend your change and its cost. Distinguish a finite simulation observation from a guaranteed worst-case bound.'},
 {id:'I2',title:'Prove fresh-data recovery',phase:'Independent · 15 min',setup:{mode:'ethernet',rate:100,bg:4,id:384,period:10,base:2,outage:40,deadline:5,qos:true},steps:['Run and capture the 40 ms outage case. Outage starts at 40 ms. Find link restoration and the first received sample acquired AT OR AFTER restoration.','Change acquisition period only to 15 ms. Predict the first fresh-source arrival, rerun and capture.','Compare data-age curves and explain why link-up and fresh data are different events.'],min:2,compare:'period',prompt:'Which timestamp would you use to authorize a controller restart? What additional process checks remain outside this lab?'}]},
6:{title:'Lab 6 · Networked control and timing',subtitle:'Lecture 10 · Controlled comparisons, data age and recovery',tasks:[
 {id:'P1',title:'Delay in the feedback loop',phase:'Practice · 12 min',setup:{kp:4,ki:.12,ts:.2,delay:0,jitter:0,loss:0,burst:false,limit:30,fallback:'hold',seed:42},steps:['Predict how a 4 s measurement delay might change the response. Run the zero-delay baseline and capture.','Change delay only to 4 s. Run and capture. Compare level, pump command and data age.','Use the capture overlay and metrics. Explain one overshoot using the difference between true level and received PV.'],min:2,compare:'delay',prompt:'Why can identical controller settings produce a different trajectory? State the bias and sampling assumptions.'},
 {id:'P2',title:'Burst loss and stale data',phase:'Practice · 12 min',setup:{kp:4,ki:.12,ts:.2,delay:.2,jitter:0,loss:0,burst:false,limit:3,fallback:'hold',seed:42},steps:['Capture the baseline. Predict maximum age if all acquisitions from 40 to 48 s are lost.','Enable the loss burst only. Run and capture. Locate age-limit crossings and held actuator output.','Explain the observed response. Packet loss and frozen source acquisition are different faults, even if both can age the last value.'],min:2,compare:'burst',prompt:'During the stale interval, does the simulated integrator continue accumulating? Read the model reference and explain the policy.'},
 {id:'I1',title:'Mitigate delayed control',phase:'Independent · 14 min',setup:{kp:4,ki:.12,ts:.2,delay:4,jitter:0,loss:0,burst:false,limit:30,fallback:'hold',seed:42},steps:['Capture the supplied delayed baseline. Keep delay=4 s, Ts=0.2 s and all network conditions unchanged.','Tune Kp and/or Ki to reduce peak level without increasing IAE by more than 10% relative to your baseline. Use equal 120 s windows.','Capture a candidate and calculate both comparisons. If no candidate meets both conditions, report the tradeoff rather than changing the requirement.'],min:2,compare:'gains',prompt:'Provide numerical evidence, parameter units and a limitation. This is a constrained candidate search, not proof of globally optimal PID gains.'},
 {id:'I2',title:'A recovery policy',phase:'Independent · 12 min',setup:{kp:4,ki:.12,ts:.2,delay:.2,jitter:0,loss:0,burst:true,limit:3,fallback:'hold',seed:42},steps:['Capture the hold-output baseline during the 40–48 s acquisition-loss burst.','Change only fallback to Stop inlet or Local control. Run and capture. Local control assumes a separate available local measurement path.','Compare peak level, IAE, output and recovery after the common load step at 60 s. Defend a policy for THIS inlet-pump tank.'],min:2,compare:'fallback',prompt:'Why is your choice not a universal safe state for every plant? Distinguish communication restoration from physical recovery.'}]}
};
