/* Self-contained readable report; student text is escaped, never executed. */
(function(root){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const text=v=>v===undefined||v===null||String(v).trim()===''?'Not provided':String(v);
 const prose=v=>'<p class="answer">'+esc(text(v))+'</p>';
 function table(headers,rows){return rows.length?'<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(text(v))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':prose('Not provided');}
 function csvRows(raw){
  const rows=[];let row=[],cell='',quoted=false;
  for(let i=0;i<String(raw||'').length;i++){const c=raw[i];if(c==='"'){if(quoted&&raw[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}
  if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows.filter(r=>r.some(c=>c.trim()));
 }
 function inventory(raw){const rows=csvRows(raw);return rows.length?table(rows[0],rows.slice(1)):prose('Not provided');}
 function checkpointRows(records){return records.map(s=>[s.label,'#'+s.sample_id+' / '+s.sim_time_ms+' ms',s.config,'CH'+s.channel+' / ×'+s.gain,s.raw_code,s.status,s.settled?'Settled':'Transient',s.input_voltage_V,s.reconstructed_voltage_V,s.tag_level_m??'N/A',s.fault]);}
 const checkpointHeaders=['Label','Sample / time','CONFIG','Channel / gain','Raw code','STATUS','Settling','Input V','Reconstructed V','Level m','Fault'];
 function build(data){
  const saved=data.checkpoints||[],predictions=data.predictions||[],responses=data.explanations||[],samples=data.samples||[],actions=data.procedure?.actions||[];
  const expectations=data.task_expectations;
  const tasks=Object.entries(expectations||{}).filter(([,task])=>task.phase==='independent').map(([key,task])=>[key,task.title,task]);
  const contents=tasks.map(([key,title,task])=>{
   const ps=predictions.filter(p=>p.task===key),rs=responses.filter(r=>r.task===key),cs=saved.filter(s=>s.assignment===key&&s.learning_phase==='independent');
   const responseKeys=task.responses||[];
   const answers=responseKeys.map(({key:k,title:heading})=>{const versions=rs.filter(r=>r.key===k),r=versions.at(-1),s=samples.find(x=>x.sample_id===r?.sample_id);return '<h3>'+esc(heading||k)+'</h3>'+prose(r?.text)+(r?'<p class="meta">Saved '+esc(r.recorded_at)+' · Sample reference '+esc(r.sample_id??'none')+' · '+versions.length+' saved version(s)</p>':'')+(s?table(['Referenced sample','CONFIG','CH / gain','Raw','STATUS','Settled','Input V'],[[s.sample_id,s.config,'CH'+s.channel+' / ×'+s.gain,s.raw_code,s.status,s.settled?'Yes':'No',s.input_voltage_V]]):'');}).join('');
   const logs=actions.filter(a=>a.task===key&&['write','configRead','dacWrite','dacRead'].includes(a.id));
   return '<section class="task"><h2>'+esc(title)+'</h2><h3>Prediction</h3>'+(!task.prediction_required?prose('Not required for this task.'):prose(ps.at(-1)?.text))+(ps.length?'<p class="meta">Latest of '+ps.length+' saved prediction(s). Recorded '+esc(ps.at(-1).recorded_at)+'. Full revision history is in the JSON.</p>':'')+answers+'<h3>Saved independent checkpoints</h3>'+table(checkpointHeaders,checkpointRows(cs))+'<h3>Configuration and feedback records</h3>'+table(['Action #','Operation','Requested CONFIG','IC CONFIG','DAC code','Returned value'],logs.map(a=>[a.seq,a.id,a.id==='write'?'0x'+Number(a.request).toString(16).toUpperCase().padStart(2,'0'):'—','0x'+Number(a.config).toString(16).toUpperCase().padStart(2,'0'),a.dac,a.id.endsWith('Read')?a.readback:'—']))+'</section>';
  }).join('');
  const missing=[];if(!expectations)missing.push('Task requirements unavailable in this older export; completeness cannot be assessed. Regenerate the report from the current workbench');if(!String(data.group||'').trim())missing.push('Group / student names');
  for(const [k,title,task]of tasks){if(task.checkpoint_required&&!saved.some(s=>s.assignment===k&&s.learning_phase==='independent'))missing.push(title+': checkpoint');if(task.prediction_required&&!predictions.some(p=>p.task===k&&p.text?.trim()))missing.push(title+': prediction');for(const {key:part} of task.responses||[])if(!responses.some(r=>r.task===k&&r.key===part&&r.text?.trim()))missing.push(title+': '+part+' explanation');}
  if(!String(data.notes||'').trim())missing.push('Final discussion / limitation');
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EE4002 Lab 1 Report</title><style>'+css+'</style></head><body><main><header><p class="eyebrow">EE4002 · LAB 1 · SIMULATION REPORT</p><h1>IC Configuration and Measurement Evidence</h1><p><strong>Group / students:</strong> '+esc(text(data.group))+'</p><p class="meta">Generated '+esc(data.exported_at)+' · '+esc(text(data.model))+'</p></header><aside class="print-help">Local report only — nothing has been submitted. Open this HTML in a browser and use Print → Save as PDF if preferred. Upload the report (HTML or PDF) and EE4002_Lab1_evidence.json to Moodle yourself. Regenerate both files after changing your work.</aside><section><h2>Evidence review</h2>'+prose(missing.length?'Missing saved items: '+missing.join('; '):'Core saved items are present. This is not a correctness check or a grade.')+'<p>Asset and flow tables below must also be checked manually; prefilled rows are not proof of completion. Only saved predictions and explanations are included. Unsaved drafts are not treated as answers. All measurements are simulated.</p></section>'+contents+'<section><h2>System assets</h2>'+inventory(data.assets_csv)+'<h2>Data flows</h2>'+inventory(data.flows_csv)+'<h2>Final discussion and simulation limitations</h2>'+prose(data.notes)+'</section><section><h2>Appendix · Other checkpoints</h2><p>Practice or older unclassified records are not substitutes for the independent tasks.</p>'+table(checkpointHeaders,checkpointRows(saved.filter(s=>s.learning_phase!=='independent'||!tasks.some(([k])=>k===s.assignment))))+'</section><footer>Student-entered answers are reproduced without automatic correction. Full samples, transactions, faults and revision history are retained in the JSON evidence file. This report does not certify physical hardware performance.</footer></main></body></html>';
 }
 const css='*{box-sizing:border-box}body{margin:0;background:#edf1f4;color:#172b3c;font:16px/1.55 Arial,Helvetica,sans-serif}main{max-width:1180px;margin:24px auto;padding:36px;background:white}h1{font-size:30px;line-height:1.2}h2{font-size:23px;color:#175e76;margin:28px 0 12px;border-bottom:2px solid #175e76;padding-bottom:6px}h3{font-size:18px;margin:20px 0 8px}.eyebrow{font-size:14px;letter-spacing:1px;color:#175e76}.meta,footer{font-size:14px;color:#526677}.answer{white-space:pre-wrap;overflow-wrap:anywhere;border-left:3px solid #bd7914;padding:10px 14px;background:#f7f9fa}.print-help{padding:16px;background:#e9f2f6;border:1px solid #becdd7}.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:14px;margin:12px 0}td,th{border:1px solid #cbd5df;padding:8px;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{background:#e9f2f6}footer{margin-top:30px;border-top:1px solid #cbd5df;padding-top:14px}@media(max-width:650px){main{padding:18px;margin:0}h1{font-size:25px}}@page{size:A4 landscape;margin:14mm}@media print{body{background:white;font-size:11pt}main{margin:0;padding:0;max-width:none}.print-help{display:none}.task{break-before:page}h2,h3{break-after:avoid}thead{display:table-header-group}tr{break-inside:avoid}table{font-size:9pt;table-layout:fixed}td,th{padding:5px}.table-wrap{overflow:visible}.answer{background:white}footer{font-size:9pt}}';
 root.LabReport={build,csvRows};if(typeof module!=='undefined')module.exports=root.LabReport;
})(typeof window!=='undefined'?window:globalThis);
