/* Generated by scripts/build-lab1.cjs from lab1/src; edit the sources, then rebuild. */
(function(){
'use strict';

// ---- core ----
const {Workbench,hex}=EE4002;const lab=new Workbench();const $=id=>document.getElementById(id);
const hooks={render:[],task:[],action:[],update:[]};
let renderPending=false,ready=false;
function emit(kind,...args){for(const fn of hooks[kind]){try{fn(...args);}catch(error){console.error('Lab UI '+kind,error);message('Display update failed: '+error.message);$('message').className='error';}}}
function render(){if(!ready||renderPending)return;renderPending=true;requestAnimationFrame(()=>{renderPending=false;try{renderBase();}catch(error){console.error('Lab base display',error);message('Display update failed: '+error.message);$('message').className='error';}emit('render');emit('update');});}
function runAction(id,f){try{f();emit('action',id);update();}catch(error){message(error.message);$('message').className='error';emit('update');render();}}
const safe=f=>event=>runAction(event?.currentTarget?.id||'operation',f);
function message(s){$('message').textContent=s;$('message').className='';}
function encoded(){return (+$('en').value<<7)|(+$('gain').value<<4)|(+$('mux').value<<2)|+$('rate').value;}
let lastSampleCount=-1,lastEventCount=-1;
function renderBase(){const b=encoded();$('encoded').textContent=hex(b)+' / '+b.toString(2).padStart(8,'0');$('levelValue').textContent=lab.level.toFixed(2)+' m';$('current').textContent=lab.current.toFixed(3)+' mA';$('voltage').textContent=(lab.current*.15).toFixed(3)+' V';$('ref').textContent=lab.ref.toFixed(3)+' V';$('dacV').textContent=(lab.dac*3.3/4096).toFixed(6)+' V';$('actualConfig').textContent=hex(lab.config);$('raw').textContent=lab.code+' / '+hex(lab.code,3);$('status').textContent=hex(lab.status);$('time').textContent='Simulation time: '+lab.time.toFixed(1)+' ms';$('savedCount').textContent=lab.saved.length+' checkpoints saved';const flags=['DRDY','OVERRANGE','SETTLING','REF_ERROR','SPI_ERROR','OVERRUN'].filter((x,i)=>lab.status&(1<<i));$('flags').textContent=(lab.enabled?'Enabled':'Stopped')+' · '+(flags.join(', ')||'No flags');const s=lab.samples.at(-1);if(s){$('rawTag').textContent=s.raw_code;$('vinTag').textContent=formatNumber(s.reconstructed_voltage_V,6)+' V';$('levelTag').textContent=s.channel===0?formatNumber(s.tag_level_m,4)+' m':'N/A: channel is not the tank shunt';$('ageTag').textContent=s.source_age_ms+' ms / '+s.sim_time_ms+' ms';}else{['rawTag','vinTag','levelTag','ageTag'].forEach(id=>$(id).textContent='—');} if(lastSampleCount!==lab.samples.length){$('history').replaceChildren(...lab.samples.slice(-15).reverse().map(s=>row([s.sample_id,s.sim_time_ms,s.channel,s.raw_code,s.status,s.settled?'Yes':'No'])));lastSampleCount=lab.samples.length;}if(lastEventCount!==lab.events.length){$('transactions').replaceChildren(...lab.events.filter(e=>e.type==='SPI').slice(-12).reverse().map(e=>row([e.event_id,e.sim_time_ms,e.mode,e.tx,e.rx])));lastEventCount=lab.events.length;}draw();}
function row(values){const tr=document.createElement('tr');values.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});return tr;}
function draw(){const canvas=$('trend'),w=canvas.clientWidth,h=240,dpr=window.devicePixelRatio||1;if(w<1)return;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);c.font='14px Arial';c.fillStyle='#243e50';c.fillText('ADC code',12,20);c.fillText('Simulation time (ms)',Math.max(65,w-170),233);const l=60,r=w-20,t=32,b=195;c.strokeStyle='#c7d2db';[0,2048,4095].forEach(v=>{const y=b-v/4095*(b-t);c.beginPath();c.moveTo(l,y);c.lineTo(r,y);c.stroke();c.fillText(v,7,y+5);});const ss=lab.samples.slice(-30);if(!ss.length)return;const min=ss[0].sim_time_ms,max=Math.max(min+1,ss.at(-1).sim_time_ms);c.fillText(Math.round(min),l,216);c.fillText(Math.round(max),Math.max(l+48,r-42),216);c.strokeStyle='#147489';c.lineWidth=2;c.beginPath();ss.forEach((s,i)=>{const x=l+(s.sim_time_ms-min)/(max-min)*(r-l),y=b-s.raw_code/4095*(b-t);i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();ss.forEach(s=>{c.fillStyle=s.settled?'#147489':'#b2680d';c.beginPath();c.arc(l+(s.sim_time_ms-min)/(max-min)*(r-l),b-s.raw_code/4095*(b-t),4,0,Math.PI*2);c.fill();});}
['en','gain','mux','rate'].forEach(id=>$(id).onchange=safe(()=>{}));
$('level').oninput=safe(()=>{lab.level=+$('level').value;});$('pot').onchange=safe(()=>{const v=+$('pot').value;if(!Number.isFinite(v)||v<0||v>3.3)throw Error('Test voltage must be 0–3.3 V.');lab.pot=v;});$('assumed').onchange=safe(()=>{lab.assumedRef=+$('assumed').value;message('Software assumption changed. Acquire a new sample to reconstruct with it.');});$('fault').onchange=safe(()=>{lab.setFault($('fault').value);message('Fault scenario changed. Existing evidence is preserved.');});$('spi').onchange=safe(()=>lab.spiMode=+$('spi').value);
$('copy').onclick=safe(()=>$('config').value=hex(encoded()));$('write').onclick=safe(()=>{const str=$('config').value.trim();if(!/^(0x[0-9a-f]{1,2}|\d{1,3})$/i.test(str))throw Error('Use a byte such as 0x81 or decimal 129.');lab.write(1,Number(str));message('Write sent. Read CONFIG to verify the accepted state.');});$('idRead').onclick=safe(()=>$('readback').textContent='ID = '+hex(lab.read(0)));$('configRead').onclick=safe(()=>$('readback').textContent='CONFIG read-back = '+hex(lab.read(1)));$('statusRead').onclick=safe(()=>$('readback').textContent='STATUS read-back = '+hex(lab.read(2)));$('clear').onclick=safe(()=>{lab.write(2,48);message('Sent W1C mask 0x30 for SPI_ERROR and OVERRUN. Evidence log retained.');});$('dacWrite').onclick=safe(()=>{lab.writeDac(Number($('dac').value));message('DAC write sent. Read its registers, then measure CH2.');});$('dacRead').onclick=safe(()=>$('readback').textContent='DAC = '+((lab.read(5)<<8)|lab.read(6)));
$('step').onclick=safe(()=>{const s=lab.step();message(s?'Output generated. Read STATUS and DATA.':'No conversion: CONFIG.EN is zero.');});$('three').onclick=safe(()=>{for(let i=0;i<3;i++){lab.step();lab.read(2);lab.read(3);lab.read(4);}message('Three periods elapsed; each output and status was recorded and read.');});$('dataRead').onclick=safe(()=>{const hi=lab.read(3),lo=lab.read(4);$('readback').textContent='DATA = '+((hi<<8)|lo)+'; reading DATA_L clears DRDY';});$('reset').onclick=safe(()=>{lab.reset();$('readback').textContent='ICs reset. Read ID and CONFIG again.';message('Reset preserved evidence and faults. Select None to remove a fault.');});$('save').onclick=safe(()=>{if(!$('label').value.trim())throw Error('Give this checkpoint a label.');const record=lab.save($('label').value.trim());Object.assign(record,{assignment:activeTask,learning_phase:LabSteps.plans[activeTask]?.phase||'practice'});message('Checkpoint saved. Export before closing.');});
document.querySelector('#measurement table').createCaption().textContent='Last recorded conversion. Generate a new sample after changing inputs or configuration.';
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=safe(()=>{download('EE4002_Lab1_evidence.json',JSON.stringify(collectLabEvidence(),null,2),'application/json');message('Download requested. Find EE4002_Lab1_evidence.json in your downloads, check it, then upload it yourself to Moodle. Nothing has been submitted by this page.');});$('csv').onclick=safe(()=>{if(!lab.samples.length)throw Error('Generate samples before exporting CSV.');const keys=Object.keys(lab.samples[0]);const quote=x=>'"'+String(x).replaceAll('"','""')+'"';download('EE4002_Lab1_samples.csv',[keys.join(','),...lab.samples.map(s=>keys.map(k=>quote(s[k])).join(','))].join('\n'),'text/csv');message('Sample history exported.');});window.addEventListener('resize',render);

function collectLabEvidence(){return {model:LabConfig.modelName,app_version:LabConfig.appVersion,evidence_schema:LabConfig.evidenceSchema,task_expectations:LabSteps.expectations(),task_titles:Object.fromEntries(Object.entries(LabSteps.plans).map(([k,p])=>[k,p.title])),simulation_only:true,learning_design:'step-by-step practice then independent',predictions:lab.predictions||[],explanations:lab.responses||[],procedure:lab.workflow||null,exported_at:new Date().toISOString(),group:$('group').value,notes:$('notes').value,assets_csv:$('assets').value,flows_csv:$('flows').value,checkpoints:lab.saved,samples:lab.samples,events:lab.events};}

function formatNumber(value,digits){return typeof value==='number'&&Number.isFinite(value)?value.toFixed(digits):'Not available';}


// ---- guide ----
// Guided workflow and persistence. The animation always runs in a separate frame.
const isTour=new URLSearchParams(location.search).has('tour');
const storageKey=LabConfig.storageKey;
const fields=['group','notes','assets','flows','en','gain','mux','rate','config','spi','level','pot','assumed','fault','dac','label'];
let activeTask='A',saveTimer=null,storageAvailable=true,resetting=false;
const taskData=LabSteps.tasks;
const panel=document.createElement('section');panel.id='guided';panel.innerHTML=`<div class="section-title"><span>START</span><h2>60-minute core · 15-minute buffer</h2></div><p>First practice with guidance, then complete four changed assignments independently. References remain available. Advanced SPI waveforms, vendor firmware, PID tuning and network diagnosis are outside this lab.</p><div class="toolbar"><button id="watchTour" class="primary">Watch operation walkthrough</button><a id="deviceReference" href="reference.html" target="_blank" rel="noopener">Device reference ↗</a><a href="student-guide.html" target="_blank" rel="noopener">Student guide</a><span id="draftState" role="status">Local draft</span></div><p id="restoreNotice" role="status" hidden></p><div class="task-nav" role="group" aria-label="Lab tasks"></div><h3 id="taskTitle"></h3><p id="taskGoal"></p><ol id="taskSteps"></ol><p id="taskPass"></p><div class="toolbar"><span id="prepared" role="status" hidden></span></div>`;
document.querySelector('main').prepend(panel);
const ev=document.createElement('div');ev.id='checkpointReview';ev.innerHTML='<h3>Saved checkpoints</h3><p id="coreProgress" role="status"></p><div class="table-wrap"><table><thead><tr><th>Label</th><th>CH / gain</th><th>Code</th><th>Valid settling?</th></tr></thead><tbody id="savedRows"></tbody></table></div>';
$('records').append(ev);
const feedback=document.createElement('p');feedback.id='localFeedback';feedback.setAttribute('role','status');$('registers').append(feedback);
const measureFeedback=document.createElement('p');measureFeedback.id='measureFeedback';measureFeedback.setAttribute('role','status');$('measurement').querySelector('.toolbar').after(measureFeedback);
const actions=document.createElement('div');actions.className='toolbar';actions.innerHTML='<button id="newSession">Start new session…</button><span>Local drafts survive reload on this browser when storage is available. JSON export is your portable copy.</span>';$('records').append(actions);
function showTask(key){if(!taskData[key])return;activeTask=key;const t=taskData[key];$('taskTitle').textContent=t.title;$('taskGoal').textContent=t.goal;$('taskSteps').replaceChildren(...t.steps.map(x=>{const li=document.createElement('li');li.textContent=x;return li;}));$('taskPass').textContent=t.pass;emit('task',key);update();}
function prepare(key){
 const values=LabSteps.plans[key]?.prepare;
 if(!values)return;
 $('en').value='1';$('gain').value=String(values.gain);$('mux').value=String(values.mux);$('rate').value='1';$('spi').value='0';lab.spiMode=0;$('assumed').value='3.3';lab.assumedRef=3.3;$('level').value='1';lab.level=1;$('pot').value='1';lab.pot=1;$('fault').value='none';lab.setFault('none');$('dac').value='2048';$('config').value=hex(encoded());$('label').value=LabSteps.plans[key].label;
 if(key==='C')$('dacWrite').closest('details').open=true;
 $('prepared').textContent='Fields prepared. Now Write CONFIG and Read CONFIG. No register was written.';render();update();
}
function update(){render();if(!isTour&&!resetting){clearTimeout(saveTimer);saveTimer=setTimeout(persist,800);}}
let previousSaved=-1;
hooks.update.push(()=>{
 const count=LabSteps.taskKeys('independent').filter(k=>lab.saved.some(s=>s.learning_phase==='independent'&&s.assignment===k)).length;
 $('coreProgress').textContent=count+'/'+LabSteps.taskKeys('independent').length+' independent tasks have records. Presence is not correctness or a grade.';
 if(previousSaved!==lab.saved.length){$('savedRows').replaceChildren(...lab.saved.slice(-50).map(s=>row([s.label,s.channel+' / ×'+s.gain,s.raw_code,s.settled?'Settled':'Transient'])));previousSaved=lab.saved.length;}
 $('localFeedback').textContent=$('message').textContent+' Latest read: '+$('readback').textContent;
 $('measureFeedback').textContent=$('message').textContent;
});
function persist(){try{localStorage.setItem(storageKey,JSON.stringify({schema:LabConfig.storageSchema,app_version:LabConfig.appVersion,task:activeTask,model:lab,fields:Object.fromEntries(fields.map(id=>[id,$(id).value]))}));$('draftState').textContent='Draft saved on this browser';}catch(e){storageAvailable=false;$('draftState').textContent='Storage unavailable: export JSON before leaving';}}
function restore(){if(isTour)return;try{const st=JSON.parse(localStorage.getItem(storageKey)||'null');if(st?.schema===LabConfig.storageSchema&&Array.isArray(st.model?.samples)&&Array.isArray(st.model?.saved)&&Array.isArray(st.model?.events)){Object.assign(lab,st.model);for(const [key,fallback]of Object.entries({level:1,pot:1,assumedRef:3.3,config:0,dac:0,code:0,time:0})){if(!Number.isFinite(lab[key]))lab[key]=Number.isFinite(Number(lab[key]))?Number(lab[key]):fallback;}const corrected=[];if(!['none','reference','drop','freeze','open'].includes(lab.fault)){lab.fault='none';corrected.push('fault → None / nominal');}if(![0,1].includes(lab.spiMode)){lab.spiMode=0;corrected.push('interface mode → 0');}if(corrected.length){$('restoreNotice').hidden=false;$('restoreNotice').textContent='Draft settings repaired: '+corrected.join('; ')+'. Existing records were preserved. Check settings and take a new measurement before continuing.';}for(const id of fields)if(typeof st.fields?.[id]==='string')$(id).value=st.fields[id];for(const [id,key]of Object.entries({level:'level',pot:'pot',assumed:'assumedRef',fault:'fault',spi:'spiMode'}))$(id).value=String(lab[key]);if(taskData[st.task])activeTask=st.task;$('message').textContent='Restored your local draft. Check settings before continuing.';}}catch(e){$('draftState').textContent='No restorable draft; export JSON to keep evidence.';}}
$('newSession').onclick=()=>{if(!confirm('Start a new session? Export your current evidence first. This clears only this Lab 1 draft.'))return;resetting=true;clearTimeout(saveTimer);try{localStorage.removeItem(storageKey);}catch(e){}location.reload();};
// Observe after the existing event handlers have changed model and UI.
document.addEventListener('input',e=>{if(['group','notes','assets','flows','label','config','predictionText','responseText'].includes(e.target.id))update();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!isTour&&!resetting)persist();});
window.addEventListener('pagehide',()=>{if(!isTour&&storageAvailable&&!resetting)persist();});
const dialog=document.createElement('dialog');dialog.id='tourDialog';dialog.innerHTML='<div class="toolbar"><strong>Operation walkthrough · separate practice run</strong><button id="closeTour">Close and return to my experiment</button></div><iframe title="Animated Lab 1 operation walkthrough" id="tourFrame"></iframe>';document.body.append(dialog);
$('watchTour').onclick=()=>{$('tourFrame').src='tutorial.html';dialog.showModal();if(parent!==window)parent.postMessage({type:'ee4002-tour-open'},'*');};
function stopTour(){dialog.close();$('tourFrame').src='about:blank';$('watchTour').focus();if(parent!==window)parent.postMessage({type:'ee4002-tour-close'},'*');}
window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='ee4002-host-viewport'){const h=Number(e.data.height);if(Number.isFinite(h)&&h>100){document.documentElement.style.setProperty('--host-height',h+'px');dialog.classList.add('embedded-tour');}}});
$('closeTour').onclick=stopTour;dialog.addEventListener('cancel',e=>{e.preventDefault();stopTour();});
if(isTour){document.body.classList.add('tour-practice');panel.hidden=true;actions.hidden=true;dialog.remove();}
restore();
new ResizeObserver(()=>{if(window.parent!==window)parent.postMessage({type:'ee4002-lab1-height',height:document.documentElement.scrollHeight},'*');}).observe(document.body);
// Only the walkthrough parent can control this isolated practice instance.
const tourSteps=[
 ()=>{prepare('A');return 'config';},
 ()=>{$('idRead').click();return 'readback';},
 ()=>{$('copy').click();return 'config';},
 ()=>{$('write').click();return 'write';},
 ()=>{$('configRead').click();return 'readback';},
 ()=>{$('three').click();return 'raw';},
 ()=>{$('notes').value='Example: Prepare only fills suggestions. Read CONFIG confirms acceptance. 1 m gives 12 mA and 1.8 V; the floored 12-bit code is 2234. The reconstructed level differs slightly because of quantization. In the student task, use Save explanation.';return 'notes';},
 ()=>{$('label').value='Walkthrough example (not student evidence)';$('save').click();return 'savedCount';}
];
window.addEventListener('message',event=>{
 if(!isTour||event.source!==parent||event.data?.type!=='ee4002-tour-step')return;
 const index=Number(event.data.index);if(!Number.isInteger(index)||index<0||index>=tourSteps.length)return;
 Object.assign(lab,new Workbench());$('notes').value='';$('group').value='Walkthrough practice';lab.samples=[];lab.saved=[];lab.events=[];lab.time=0;lab.reset();
 let id;for(let i=0;i<=index;i++)id=tourSteps[i]();render();update();
 document.querySelectorAll('.tour-focus').forEach(el=>el.classList.remove('tour-focus'));
 const target=$(id);target.classList.add('tour-focus');target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});
 parent.postMessage({type:'ee4002-tour-done',index},'*');
});
if(isTour)parent.postMessage({type:'ee4002-tour-ready'},'*');


// ---- visual ----
// Presentation layer only: all conversions and register transactions use Workbench.
if(!isTour){
const visual=document.createElement('section');visual.id='liveBench';
visual.innerHTML=`<div class="live-heading"><div><span class="eyebrow">LIVE SIGNAL CHAIN</span><h2>One input. Every stage visible.</h2></div><span id="liveClock">Paused</span></div>
<div class="live-layout"><div class="tank-panel"><div class="tank-scale"><span>2.00 m</span><span>1.00 m</span><span>0.00 m</span></div><div id="tankTouch" class="tank-vessel" aria-hidden="true"><div id="tankWater"></div><div id="reportedLine"></div><strong id="tankNumber">1.00 m</strong></div><label class="tank-input">Physical level <output id="vLevelText"></output><input id="vLevel" type="range" min="0" max="2" step="0.05" value="1" aria-label="Physical tank level in metres"></label><p class="visual-small">Drag the level. Dashed line: last CH0 estimate, when available.</p></div>
<div class="signal-panel"><div class="signal-stages"><div><span>TRANSMITTER</span><strong id="vCurrent"></strong><small>4 + 8h mA</small></div><div><span>150 Ω SHUNT</span><strong id="vShunt"></strong><small>V = I × R</small></div><div><span>MUX / PGA</span><strong id="vInput"></strong><small id="vRange"></small></div><div><span>ADC DATA</span><strong id="vCode"></strong><small id="vEstimate"></small></div></div>
<div class="visual-fields"><label>Proposed channel<select id="vMux"><option value="0">CH0 · tank</option><option value="1">CH1 · test source</option><option value="2">CH2 · DAC loopback</option><option value="3">CH3 · ground</option></select></label><label>Proposed gain<select id="vGain"><option value="0">×1</option><option value="1">×2</option><option value="2">×4</option><option value="3">×8</option></select></label><label>Proposed rate<select id="vRate"><option value="0">5 SPS</option><option value="1">20 SPS</option><option value="2">100 SPS</option><option value="3">1000 SPS</option></select></label></div>
<div class="toolbar"><button id="vWrite">Write proposed CONFIG</button><button id="vRead">Read CONFIG</button><button id="vStep" class="primary">Sample + read</button><button id="vPlay">Play slowly</button></div><p id="liveMeaning" role="status"></p><p class="visual-small">Play shows two conversions per wall-clock second. CONFIG rate sets simulation time; this is slowed playback, not real-time acquisition. Pause before saving evidence.</p></div></div>
<div class="register-strip"><div><h3>Proposed CONFIG <span id="vProposed"></span></h3><div id="proposedBits" class="bits"></div></div><div><h3>IC CONFIG <span id="vAccepted"></span></h3><div id="acceptedBits" class="bits"></div></div><div><h3>STATUS now <span id="vStatus"></span></h3><div id="statusBits" class="bits"></div></div></div><p class="visual-small">CONFIG: EN · reserved · GAIN[1:0] · MUX[1:0] · RATE[1:0]. IC state is simulator instrumentation; use Read CONFIG as transaction evidence. DATA: <code id="dataBits"></code></p>
<details id="signalHistory" open><summary>Linked signal history <span class="visual-small">shared simulation time</span></summary><canvas id="signalChart" height="330" role="img" aria-label="Physical level, transmitter current and ADC code on a shared time axis"></canvas><p class="visual-small">Input snapshots at conversion times, not an oscilloscope capture. Orange ADC points are transient. Channel/gain changes break the code trace. Dragging while paused changes the live input, not historical samples.</p></details>`;
document.querySelector('main').prepend(visual);
const guideLink=document.createElement('a');guideLink.href='#guided';guideLink.textContent='Task steps ↓';guideLink.className='visual-guide-link';visual.querySelector('.live-heading').append(guideLink);
let timer=null;
const faultLabel=document.createElement('label');faultLabel.textContent='Fault injection';const faultSelect=$('fault').cloneNode(true);faultSelect.id='vFault';faultLabel.append(faultSelect);visual.querySelector('.visual-fields').append(faultLabel);
const set=(id,text)=>$(id).textContent=text;
function stop(){clearInterval(timer);timer=null;set('vPlay','Play slowly');set('liveClock','Paused');}
function sample(){if(!lab.enabled){message('Enable the ADC: prepare Task A, or set Enable to 1 below, then write CONFIG.');stop();render();update();return;}lab.step();lab.read(2);lab.read(3);lab.read(4);message('One conversion recorded and read. DRDY cleared by DATA_L read.');render();update();}
function changeLevel(value){$('level').value=String(Math.max(0,Math.min(2,Math.round(value*20)/20)));$('level').dispatchEvent(new Event('input',{bubbles:true}));}
$('vLevel').oninput=()=>changeLevel(+$('vLevel').value);
$('tankTouch').onpointerdown=e=>{e.preventDefault();$('tankTouch').setPointerCapture(e.pointerId);const move=ev=>{const r=$('tankTouch').getBoundingClientRect();changeLevel(2*(1-(ev.clientY-r.top)/r.height));};move(e);$('tankTouch').onpointermove=move;};
$('tankTouch').onpointerup=$('tankTouch').onpointercancel=()=>{$('tankTouch').onpointermove=null;};
for(const [proxy,source]of [['vMux','mux'],['vGain','gain'],['vRate','rate'],['vFault','fault']])$(proxy).onchange=()=>{$(source).value=$(proxy).value;$(source).dispatchEvent(new Event('change',{bubbles:true}));};
$('vWrite').onclick=()=>{$('copy').click();$('write').click();};$('vRead').onclick=()=>$('configRead').click();$('vStep').onclick=()=>{stop();sample();};$('vPlay').onclick=()=>{if(timer){stop();return;}if(!lab.enabled){sample();return;}set('vPlay','Pause');set('liveClock','Slow playback');timer=setInterval(sample,500);};
// Keep checkpoints deterministic and stop unattended playback on navigation.
for(const id of ['save','export','csv','reset','newSession','watchTour','prepare','write','dacWrite','step','three'])$(id)?.addEventListener('click',stop,true);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='ee4002-lab-hidden')stop();});
function bits(id,value,kind){const host=$(id);if(!host.children.length)for(let i=7;i>=0;i--){const b=document.createElement('span');b.className='bit';b.dataset.bit=i;host.append(b);}for(const b of host.children){const i=+b.dataset.bit,v=(value>>i)&1,old=b.dataset.value;b.dataset.value=v;b.classList.toggle('on',!!v);b.classList.toggle('changed',old!==undefined&&old!==String(v));b.textContent=i+': '+v;b.title=kind==='status'?['DRDY','OVERRANGE','SETTLING','REF_ERROR (reserved)','SPI_ERROR','OVERRUN','reserved','reserved'][i]:['RATE0','RATE1','MUX0','MUX1','GAIN0','GAIN1','reserved','EN'][i];}}
function paintSignals(){
set('vLevelText',lab.level.toFixed(2)+' m');$('vLevel').value=lab.level;set('tankNumber',lab.level.toFixed(2)+' m');$('tankWater').style.height=lab.level/2*100+'%';
set('vCurrent',lab.current.toFixed(2)+' mA');set('vShunt',(lab.current*.15).toFixed(3)+' V');set('vInput','CH'+lab.channel+' · ×'+lab.gain);set('vRange',(lab.inputVoltage*lab.gain).toFixed(3)+' V / '+lab.ref.toFixed(1)+' V limit');set('vCode',lab.sampleTime===null?'No sample':lab.code+' / '+hex(lab.code,3));
const s=lab.samples.at(-1),estimate=s&&s.channel===0?s.tag_level_m:null;$('reportedLine').hidden=estimate===null||lab.sampleTime===null;$('reportedLine').style.bottom=Math.max(0,Math.min(100,(estimate||0)/2*100))+'%';
set('vEstimate',s&&lab.sampleTime!==null?'Last conversion: '+s.sim_time_ms+' ms':'Write CONFIG, then sample');
for(const [proxy,source]of [['vMux','mux'],['vGain','gain'],['vRate','rate'],['vFault','fault']])$(proxy).value=$(source).value;
set('vProposed',hex(encoded()));set('vAccepted',hex(lab.config));set('vStatus',hex(lab.status));bits('proposedBits',encoded());bits('acceptedBits',lab.config);bits('statusBits',lab.status,'status');set('dataBits',lab.code.toString(2).padStart(12,'0').replace(/(.{4})(?=.)/g,'$1 ')+' (12 bits)');
const pending=!s||lab.sampleTime===null||s.config!==hex(lab.config)||s.physical_level_m!==lab.level||s.fault!==lab.fault||s.assumed_reference_V!==lab.assumedRef||s.input_voltage_V!==+lab.inputVoltage.toFixed(6);
let explanation=!lab.enabled?'ADC stopped. Proposed settings have not enabled the IC.':pending?'Input or configuration changed. ADC DATA still holds the previous conversion.':s&&!s.settled?'Transient output: SETTLING was set at conversion.':s&&(parseInt(s.status,16)&2)?'Saturated output: OVERRANGE was set. A numerical result is not a valid measurement.':'Latest conversion is settled. Check reference, channel and fault state before trusting it.';
if(lab.fault==='freeze')explanation+=' Frozen transmitter: tank motion no longer changes the current.';
if(encoded()!==lab.config)explanation+=' Proposed CONFIG differs from IC state.';
set('liveMeaning',explanation);visual.classList.toggle('signal-alert',lab.fault!=='none'||!!(lab.live&2));
drawSignals();
}
function drawSignals(){const cv=$('signalChart'),w=cv.clientWidth;if(w<50)return;const h=330,dpr=devicePixelRatio||1;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d');c.scale(dpr,dpr);const css=getComputedStyle(visual),ink=css.color,grid=css.getPropertyValue('--visual-line')||'#cbd5df';c.font='13px Arial';const ss=lab.samples.slice(-60),l=58,r=w-18,min=ss[0]?.sim_time_ms||0,max=Math.max(min+1,ss.at(-1)?.sim_time_ms||1);const lanes=[{key:'physical_level_m',max:2,name:'Level (m)',color:'#b85a20'},{key:'source_current_mA',max:20,name:'Current (mA)',color:'#087c83'},{key:'raw_code',max:4095,name:'ADC code',color:'#286faf'}];
lanes.forEach((a,k)=>{const top=25+k*96,bottom=top+65;c.fillStyle=ink;c.fillText(a.name,l,top-8);c.fillText(String(a.max),5,top+5);c.fillText('0',28,bottom+3);c.strokeStyle=grid;c.beginPath();c.moveTo(l,top);c.lineTo(r,top);c.moveTo(l,bottom);c.lineTo(r,bottom);c.stroke();let prev=null;c.strokeStyle=a.color;c.lineWidth=2;for(const s of ss){const val=s[a.key];if(!Number.isFinite(val)){prev=null;continue;}const x=l+(s.sim_time_ms-min)/(max-min)*(r-l),y=bottom-val/a.max*(bottom-top);if(prev&&(k!==2||prev.s.config===s.config)){c.beginPath();c.moveTo(prev.x,prev.y);c.lineTo(x,y);c.stroke();}c.fillStyle=k===2&&!s.settled?'#b85a20':a.color;c.beginPath();c.arc(x,y,3,0,Math.PI*2);c.fill();prev={x,y,s};}});
c.fillStyle=ink;c.fillText(Math.round(min)+' ms',l,318);c.textAlign='right';c.fillText(Math.round(max)+' ms',r,318);c.textAlign='left';if(!ss.length)c.fillText('Sample to begin the history',l,152);
}
hooks.render.push(()=>{if($('liveBench').getClientRects().length)paintSignals();});new ResizeObserver(()=>render()).observe($('signalChart'));document.addEventListener('toggle',e=>{if(e.target.id==='extraVisual'||e.target.id==='signalHistory')render();},true);
}


// ---- lesson ----
if(!isTour){
document.body.classList.add('student-workflow');document.querySelector('main').prepend($('guided'));
const order=[...LabSteps.taskKeys(),'Submit'],independent=k=>LabSteps.plans[k]?.phase==='independent';lab.predictions=lab.predictions||[];
const intro=document.createElement('p');intro.className='workflow-instruction';$('guided').prepend(intro);
const nav=$('guided').querySelector('.task-nav');nav.replaceChildren();for(const [label,key]of [['1 · Practice','A'],['2 · Independent work','E'],['3 · Save locally','Submit']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{showTask(key);update();};nav.append(b);}
const chooser=document.createElement('label');chooser.textContent='Current task ';const select=document.createElement('select');select.id='lessonTask';chooser.append(select);nav.after(chooser);select.onchange=()=>{showTask(select.value);update();};
const pred=document.createElement('section');pred.id='predictionBox';pred.innerHTML='<h3>Predict before measuring</h3><label>Your calculation or prediction<textarea id="predictionText" rows="3" placeholder="Include units and reasoning. No model answer is shown here."></textarea></label><button id="recordPrediction">Record prediction</button><p id="predictionState" role="status"></p>';$('guided').append(pred);
$('recordPrediction').onclick=safe(()=>{const value=$('predictionText').value.trim();if(!value){$('predictionState').textContent='Enter a prediction first.';throw Error('Enter a prediction first.');}lab.predictions.push({task:activeTask,text:value,event_count:lab.events.length,sample_count:lab.samples.length,recorded_at:new Date().toISOString()});$('predictionState').textContent='Prediction recorded for export.';});
const labels={bench:'YOU SET · Test input',registers:'YOU SET · Write, then verify',measurement:'OBSERVE · Read code and status',records:'YOU RECORD · Save your evidence'};for(const[id,label]of Object.entries(labels))$(id).querySelector('h2').textContent=label;
hooks.task.push(function(key){document.body.dataset.task=key;document.body.dataset.phase=independent(key)?'independent':key==='Submit'?'submit':'practice';$('watchTour').hidden=independent(key);pred.hidden=!LabSteps.expectations()[key]?.prediction_required;const keys=key==='Submit'?['Submit']:LabSteps.taskKeys(LabSteps.plans[key].phase);select.replaceChildren(...keys.map((k,i)=>{const o=document.createElement('option');o.value=k;o.textContent=(i+1)+' · '+taskData[k].title;return o;}));select.value=key;intro.textContent=independent(key)?'INDEPENDENT WORK · Set inputs and configuration yourself. Use the device reference; prepared settings and expected answers are not provided.':key==='Submit'?'SAVE LOCALLY · Download your work, then upload the file to Moodle yourself. This page does not submit anything.':'PRACTICE · Follow the example and use Prepare fields. Ask questions now; later solve changed cases yourself.';if(key==='G')$('dacWrite').closest('details').open=true;$('prepared').textContent='';$('predictionText').value=lab.predictions.filter(p=>p.task===key).at(-1)?.text||'';$('predictionState').textContent='';});
const details=document.createElement('details');details.id='extraVisual';const summary=document.createElement('summary');summary.textContent='Optional: inspect the full signal visualization';details.append(summary);const visual=$('liveBench');if(visual){visual.before(details);details.append(visual);}
for(const d of $('records').querySelectorAll('details'))if(d.textContent.includes('Assets CSV'))d.dataset.inventory='true';

}


// ---- steps ----
if(!isTour){
 document.body.classList.add('step-workflow');
 const main=document.querySelector('main'), plans=LabSteps.plans;
 // Evidence remains intact when upgrading an older local draft.
 if(lab.workflow?.version!==LabConfig.workflowSchema)lab.workflow={version:LabConfig.workflowSchema,seq:0,actions:[],tasks:{}};
 lab.responses=lab.responses||[];
 const state=lab.workflow;
 const toolbar=$('group').closest('.toolbar');toolbar.id='sessionTools';
 const downloadNote=document.createElement('p');downloadNote.className='notice';downloadNote.textContent='Download report (HTML) for reading and Download evidence (JSON) for the original records. Open the HTML report; use Print → Save as PDF if preferred. Upload the report (HTML or PDF) and JSON to Moodle yourself. Nothing is submitted by this page. Download both again after making changes.';toolbar.prepend(downloadNote);
 const taskOverview=document.createElement('details');taskOverview.id='taskOverview';taskOverview.innerHTML='<summary>Learning goal and task overview</summary>';
 for(const id of ['taskGoal','taskSteps','taskPass'])taskOverview.append($(id));
 $('taskTitle').after(taskOverview);
 $('guided').querySelector('.section-title').hidden=true;
 $('guided').querySelector('.section-title').nextElementSibling.hidden=true;
 
 const coach=document.createElement('section');coach.id='stepCoach';coach.innerHTML='<div class="step-heading"><span id="stepNumber"></span><h2 id="stepName" tabindex="-1"></h2></div><p id="stepDo"></p><p class="step-observe"><strong>LOOK HERE</strong><br><span id="stepLook"></span></p><details><summary>Why this step matters</summary><p id="stepWhy"></p></details><button id="stepPrepare" class="primary" hidden>Prepare fields for this practice</button><p id="stepPrepared" role="status"></p>';
 const workspace=document.createElement('div');workspace.id='stepWorkspace';
 const bottom=document.createElement('section');bottom.id='stepNavigation';bottom.innerHTML='<p id="stepFeedback" role="status" aria-live="polite"></p><div class="toolbar"><button id="previousStep">← Previous step</button><button id="continueStep" class="primary">Next step →</button></div><p class="small">Step checks verify procedure, not the correctness of your explanation or an assignment grade. References and earlier tasks remain available.</p>';
 $('guided').after(coach,workspace,bottom);
 const discussion=document.createElement('section');discussion.id='pairDiscussion';coach.before(discussion);
 const responsePanel=document.createElement('section');responsePanel.id='stepResponse';responsePanel.innerHTML='<h2>Your explanation</h2><p id="responsePrompt"></p><pre id="responseEvidence"></pre><label>Reasoning and evidence<textarea id="responseText" rows="4" placeholder="Use values, units and your reasoning. Do not only write “it worked”."></textarea></label><button id="saveResponse">Save explanation</button><p id="responseSaved" role="status"></p>';
 main.append(responsePanel);
 const stageIds=['bench','registers','measurement','records','predictionBox','stepResponse'];
 const homes=new Map(stageIds.map(id=>{const node=$(id),anchor=document.createComment('home '+id);node.before(anchor);return[id,anchor];}));
 const learning=document.createElement('details');learning.id='learningMap';learning.innerHTML='<summary>What you should be able to explain after Lab 1</summary><ol><li>Trace a physical input through a sensor, shunt, converter and software tag; locate the controller and actuator in the wider loop.</li><li>Calculate level → mA → V → ADC code, including units and quantization.</li><li>Distinguish proposed fields, a sent write, accepted configuration and measured feedback.</li><li>Recognize settling and saturation; justify a usable gain.</li><li>Use a baseline, failed read-back and corrected measurement to document recovery.</li></ol><p>This simulator does not establish competence in wiring real hardware, SPI waveforms, vendor drivers, PID tuning or network diagnosis.</p>';
 $('guided').append(learning);
 // The optional visualization is observation only; there is one set of student controls.
 $('extraVisual').querySelector('summary').textContent='Optional observation: linked tank, current, ADC bits and history (no controls)';
 $('tankTouch').onpointerdown=null;$('tankTouch').onpointerup=null;$('tankTouch').onpointercancel=null;
 $('liveBench').classList.add('read-only-visual');
 $('liveBench').querySelector('.tank-panel p').textContent='Known input and last CH0 estimate. Change inputs only in the current task step.';
 $('liveBench').querySelector('.signal-panel>.visual-small').textContent='Samples advance only when you use the task’s conversion button. The chart shows simulated samples, not a physical waveform.';
 $('copy').textContent='① Copy encoder to write box';$('write').textContent='② Write CONFIG';$('configRead').textContent='③ Read CONFIG';
 $('recordPrediction').textContent='Record prediction';
 $('watchTour').textContent='Optional: button demonstration';
 $('notes').closest('label').firstChild.textContent='Final discussion and simulation limitation (task explanations are saved separately)';
 $('notes').placeholder='State your discussion conclusion and one limitation. Saved task explanations are included automatically; no need to copy them here.';
 $('taskTitle').textContent=taskData[activeTask].title;
 function logAction(id){
  const lastEvents=lab.events.slice(-4);
  state.actions.push({seq:++state.seq,id,task:activeTask,step:position(),request:Number($('config').value),config:lab.config,dac:lab.dac,readback:$('readback').textContent,dropped:lastEvents.some(e=>e.type==='WRITE_DROPPED'),sample_count:lab.samples.length});
 }
 function taskState(){return state.tasks[activeTask]||(state.tasks[activeTask]={index:0,entries:{}});}
 function position(){return taskState().index;}
 function current(){return plans[activeTask]?.steps[position()];}
 function entry(){const t=taskState();return t.entries[t.index]||(t.entries[t.index]={action:state.seq,sample:lab.samples.at(-1)?.sample_id||0,saved:lab.saved.length});}
 function check(){const s=current();return !!s&&LabSteps.evaluate(s,{lab,task:activeTask,actions:state.actions,entry:entry(),proposed:encoded(),writeBox:Number($('config').value),predictions:lab.predictions,responses:lab.responses});}
 function refresh(){
  if(!current())return;
  const okay=check();$('continueStep').disabled=!okay;
  $('stepFeedback').className=okay?'step-pass':'step-wait';
  $('stepFeedback').textContent=okay?'Step conditions met. Read the observation prompt, then continue.':hint(current().gate);
  if(!okay&&['input','nominal'].includes(current().gate)){
   const issues=LabSteps.inputIssues(current(),lab);
   $('stepFeedback').textContent=issues.length?issues.join(' '):'Click Prepare fields for this practice.';
  }
  if(!okay&&$('message').classList.contains('error'))$('stepFeedback').textContent=$('message').textContent+' '+hint(current().gate);
  $('stepPrepared').textContent=$('prepared').textContent;
 }
 function hint(gate){return ({config:'Waiting: choose fields → copy → write → read back. If values differ, repeat the sequence after checking the fields.',rejected:'Waiting: with the dropped-write fault selected, copy the CH1 request, write it, and read back the unchanged configuration.',sample:'Waiting: acquire three conversions for the current settings. Settling must end; saturation may be the intended observation.',prediction:'Waiting: record a prediction for this task before sampling.',response:'Waiting: save your explanation below. Text is retained with your evidence; it is not automatically graded.',save:'Waiting: save a new checkpoint for this task. If settings changed, go back and acquire a new sample.',dac:'Waiting: write the specified DAC code, then read its registers.',input:'Waiting: set the task’s known input and nominal reference/fault conditions. Practice begins with Prepare fields.',id:'Waiting: click Read ID and check the returned identity.',fault:'Waiting: select the stated fault condition and test voltage.',nominal:'Waiting: set nominal fault/reference conditions.',prepared:'Waiting: click Prepare fields. No IC registers will be written.'})[gate]||'Complete the operation above.';}
 function keepOnly(section,ids){
  const roots=ids.map(id=>$(id)).filter(Boolean).map(el=>el.matches('input,select,textarea')?el.closest('label')||el:el.matches('td')?el.closest('tr'):el.id==='encoded'?el.closest('strong'):el.parentElement.matches('.readout>span')?el.parentElement:el);
  const walk=node=>{for(const child of node.children){if(roots.some(r=>r===child||r.contains(child)))continue;if(roots.some(r=>child.contains(r)))walk(child);else child.classList.add('step-pruned');}};
  walk(section);
 }
 function paint(focus=false){
  document.querySelectorAll('.step-pruned').forEach(el=>el.classList.remove('step-pruned'));
  for(const id of stageIds){const node=$(id);homes.get(id).after(node);node.classList.add('step-inactive');}
  const s=current(),submit=activeTask==='Submit';
  discussion.hidden=!(submit||activeTask==='E'&&position()===0);
  discussion.textContent=submit?'PAIR DISCUSSION · 3 minutes: Does matching register read-back prove the measured physical quantity is correct? Give one counterexample and record a simulation limitation in final Notes.':'PAIR DISCUSSION · 3 minutes: Sketch level → sensor → shunt → ADC → software tag. Add the controller and actuator to close the loop. Which parts are actually simulated here? Use this sketch for your two asset rows and one flow row at submission.';
  coach.hidden=bottom.hidden=submit;toolbar.hidden=!submit;
  document.body.dataset.stepArea=s?.area||'submit';
  document.body.dataset.stepGate=s?.gate||'submit';
  $('extraVisual').hidden=submit||s?.area==='prediction';
  $('predictionBox').hidden=true;
  if(submit){$('records').classList.remove('step-inactive');workspace.append($('records'));$('records').querySelector('[data-inventory]').open=true;updateSubmission();return;}
  entry();
  $('stepNumber').textContent=(plans[activeTask]?.phase==='independent'?'INDEPENDENT':'PRACTICE')+' · STEP '+(position()+1)+' / '+plans[activeTask].steps.length;
  $('stepName').textContent=s.name;$('stepDo').textContent=s.instruction;$('stepLook').textContent=s.observe;$('stepWhy').textContent=s.reason;
  $('stepPrepare').hidden=!s.prepare;$('stepPrepared').textContent='';
  $('previousStep').disabled=position()===0;
  $('continueStep').textContent=position()===plans[activeTask].steps.length-1?'Finish task →':'Next step →';
  const id=s.area==='prediction'?'predictionBox':s.area==='response'?'stepResponse':s.area,node=$(id);
  node.classList.remove('step-inactive');node.hidden=false;workspace.append(node);
  if(s.area==='prediction'){$('predictionText').placeholder=s.responsePrompt;node.querySelector('h3').textContent=s.responsePrompt;}
  else if(s.area==='response'){
   $('responsePrompt').textContent=s.responsePrompt;$('responseText').value=taskState().drafts?.[s.responseKey]??lab.responses.filter(r=>r.task===activeTask&&r.key===s.responseKey).at(-1)?.text??'';$('responseSaved').textContent='';
   const sample=lab.samples.at(-1);$('responseEvidence').textContent='Latest read-back: '+$('readback').textContent+'\n'+(sample?'Last sample #'+sample.sample_id+' · '+sample.config+' · CH'+sample.channel+' · gain ×'+sample.gain+'\nRaw '+sample.raw_code+' · STATUS '+sample.status+' · '+(sample.settled?'settled':'transient')+'\nReconstructed voltage '+sample.reconstructed_voltage_V+' V'+(sample.channel===0?' · level '+sample.tag_level_m+' m':''):'No measurement yet.');
  }else{if(s.gate==='save'&&!entry().labelPrepared){$('label').value=s.label;entry().labelPrepared=true;}keepOnly(node,s.allow);for(const d of node.querySelectorAll('details'))if(!d.classList.contains('step-pruned'))d.open=true;}
  refresh();render();
  if(focus){$('stepName').focus({preventScroll:true});$('stepCoach').scrollIntoView({block:'start',behavior:'instant'});}
 }
 hooks.action.push(id=>{
  if(!['prepare','copy','write','configRead','idRead','three','dacWrite','dacRead','save','recordPrediction','saveResponse'].includes(id))return;
  logAction(id);
  if(id==='recordPrediction'&&lab.predictions.at(-1)?.task===activeTask)lab.predictions.at(-1).action_seq=state.seq;
  if(id==='saveResponse'&&lab.responses.at(-1)?.task===activeTask)lab.responses.at(-1).action_seq=state.seq;
  refresh();
 });
 $('saveResponse').onclick=safe(()=>{if(!current()?.responseKey)return;const text=$('responseText').value.trim();if(!text){$('responseSaved').textContent='Write an explanation first.';throw Error('Write an explanation first.');}lab.responses.push({task:activeTask,key:current().responseKey,text,action_seq:state.seq,event_count:lab.events.length,sample_id:lab.samples.at(-1)?.sample_id||null,recorded_at:new Date().toISOString()});$('responseSaved').textContent='Explanation saved for export.';});
 $('stepPrepare').onclick=()=>runAction('prepare',()=>prepare(activeTask));
 $('previousStep').onclick=()=>{taskState().index=Math.max(0,position()-1);paint(true);update();};
 $('continueStep').onclick=()=>{if(!check()){refresh();return;}if(position()<plans[activeTask].steps.length-1){taskState().index++;paint(true);}else{taskState().finished=true;const order=[...LabSteps.taskKeys(),'Submit'];showTask(order[order.indexOf(activeTask)+1]);}update();};
 function updateSubmission(){
  const lines=LabSteps.taskKeys('independent').map(key=>{const n=lab.saved.filter(s=>s.assignment===key&&s.learning_phase==='independent').length;const rs=lab.responses.filter(r=>r.task===key).length;const ps=lab.predictions.filter(p=>p.task===key).length;return taskData[key].title+': '+n+' checkpoint(s), '+rs+' explanation(s)'+(!LabSteps.expectations()[key].prediction_required?'':', '+ps+' prediction(s)');});
  let report=$('submissionReview');if(!report){report=document.createElement('pre');report.id='submissionReview';$('records').prepend(report);}report.textContent=lines.join('\n')+'\nCounts indicate presence, not correctness. Check names, explanations, two assets, one flow and a limitation before exporting.';
 }
 let initialShow=true;
 hooks.task.push(function(key){$('taskGoal').textContent=plans[key]?.learn||taskData[key].goal;const phase=key==='Submit'?2:plans[key]?.phase==='independent'?1:0;$('guided').querySelectorAll('.task-nav button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===phase)));paint(!initialShow);if(key==='Submit'&&!initialShow)$('guided').scrollIntoView({block:'start'});initialShow=false;});
 hooks.update.push(()=>{refresh();if(activeTask==='Submit')updateSubmission();});
 // Keep incomplete writing across reloads without counting it as submitted evidence.
 $('responseText').addEventListener('input',()=>{const s=current();if(!s?.responseKey)return;taskState().drafts=taskState().drafts||{};taskState().drafts[s.responseKey]=$('responseText').value;});
 
 document.querySelector('footer').textContent='EE4002 · Lab 1 · v'+LabConfig.appVersion+' · Offline simulation';
}


// ---- host ----
if(!isTour&&new URLSearchParams(location.search).has('embedded'))document.body.classList.add('shared-embedded');


// ---- report_ui ----
if(!isTour){
 const reportButton=document.createElement('button');reportButton.id='downloadReport';reportButton.className='primary';reportButton.textContent='Download report (HTML)';$('export').before(reportButton);$('export').textContent='Download evidence (JSON)';$('export').classList.remove('primary');
 reportButton.onclick=safe(()=>{download('EE4002_Lab1_Report.html',LabReport.build(collectLabEvidence()),'text/html;charset=utf-8');message('Report download requested. Open EE4002_Lab1_Report.html to review or print to PDF. Download the JSON evidence too, then upload both files to Moodle yourself.');});
}

ready=true;showTask(activeTask);render();
})();
