/* Public workflow: procedural checks, not an answer key or an examination lock. */
(function(root){
 'use strict';
 const step=(name,area,allow,instruction,observe,reason,gate,extra={})=>({name,area,allow,instruction,observe,reason,gate,...extra});
 const input=(level,practice)=>step('Set the known input','bench',['level','fault','assumed','current','voltage','ref'],practice?'Click Prepare fields below. It sets suggestions and the test input; it does NOT write the IC.':'Set the known level to '+level.toFixed(2)+' m. Select None / nominal and the 3.3 V software reference. Do not change the input again during this test.','Known tank level, Source current and Shunt voltage. These are simulator input indicators, not ADC measurements.','A known test input lets you check the whole measurement chain.','input',{level,prepare:practice});
 const config=(text)=>step('Choose → copy → write → read','registers',['en','gain','mux','rate','encoded','copy','config','write','configRead','readback'],text+' Then click ① Copy encoder to write box, ② Write CONFIG, ③ Read CONFIG.','Compare the field encoder, CONFIG byte and CONFIG read-back. All three should agree. Changing a dropdown alone does not configure the chip.','A request is not proof of acceptance. Read-back checks the configuration the IC actually holds.','config');
 const measure=(extra='')=>step('Acquire and inspect','measurement',['three','time','raw','status','flags','rawTag','vinTag','levelTag'], 'Click Advance 3, read each. This button advances three conversion periods AND reads each result. No separate Read DATA click is needed. '+extra,'Read Raw, SETTLING / OVERRANGE and the reconstructed quantity. The latest sample must belong to your CURRENT input and configuration.','Settled only means the modeled transient has ended. It does not by itself mean correct or in range.','sample');
 const response=(key,prompt)=>step('Explain the evidence','response',[], 'Write your explanation below, referring to the actual values you observed. Then click Save explanation.','Use the last measurement and your read-back evidence shown below.','An explanation distinguishes understanding from simply producing a number.','response',{responseKey:key,responsePrompt:prompt});
 const save=label=>step('Save this checkpoint','records',['label','save','savedCount','checkpointReview'],'Enter a label such as '+label+', then click Save checkpoint. Saving does not generate a new sample.','A new row should appear for this task. Confirm the code, channel and settling state.','The checkpoint preserves the conditions and result that support your explanation.','save',{label});
 const predict=prompt=>step('Predict before measuring','prediction',[], 'Enter your prediction with formulas and units, then click Record prediction. Do not acquire this task’s samples yet.','Your own written prediction. The page will not reveal the numerical answer.','Prediction makes the subsequent measurement a test, not a number-copying exercise.','prediction',{responsePrompt:prompt});
 const dac=practice=>step('Command and read back the DAC','registers',['dac','dacWrite','dacRead','readback'], 'Enter DAC code '+(practice?2048:1024)+'. Click Write DAC code, then Read DAC registers.','Compare the commanded code with the DAC register read-back. '+(practice?'2048 × 3.3 / 4096 = 1.650 V.':'Use your prediction; the code is not a voltage unit.'),'DAC register read-back checks acceptance; the next ADC measurement adds output feedback.','dac',{dac:practice?2048:1024});
 const fail=practice=>step('Make a request that fails','bench',['fault'], 'Select Configuration writes disappear. No other fault is needed. The simulator intentionally drops writes until you remove this fault.','Fault selection only. The working CH0 configuration is still present.','A controlled failure lets you test whether your verification method actually detects a problem.','fault',{fault:'drop'});
 const rejected=practice=>step('Request CH1 and investigate','registers',['en','gain','mux','rate','encoded','copy','config','write','configRead','readback'],'Select CH1, gain ×1, enabled, 20 SPS. Copy the encoder, Write CONFIG, then Read CONFIG.','The requested byte and returned byte should differ. '+(practice?'The request is 0x85, but the chip still returns 0x81.':'Record both values; do not overwrite your failed evidence.'),'A sent command can fail silently. This is a configuration-acceptance test, not network diagnosis.','rejected');
 const remove=()=>step('Remove the fault','bench',['fault','pot'],'Select None / nominal. Set the CH1 test voltage to 1.00 V. Removing a fault does not retry a previous write.','Fault selection and CH1 voltage.','Recovery requires both removing the cause and repeating the failed operation.','fault',{fault:'none'});
 const plans={
 A:{learn:'Trace level → current → voltage → code, and distinguish proposed settings from accepted settings.',steps:[input(1,true),step('Check the device identity','registers',['idRead','readback'],'Click Read ID.','ID = 0x42. This identifies the teaching model, not a real connected chip.','Confirm that you are talking to the expected modeled device.','id'),config('Use enabled, CH0, gain ×1, 20 SPS (0x81).'),measure('At 1.00 m: 12 mA → 1.800 V → floor(4096 × 1.8 / 3.3) = 2234. The reconstructed level is about 0.9999 m.'),response('result','Why did Prepare fields alone not configure the ADC? Explain the small difference between known and reconstructed level.'),save('P1-practice')]},
 B:{learn:'Recognize saturation: extra gain can make a perfectly plausible numeric output unusable.',steps:[input(1,true),config('Use enabled, CH0, gain ×2, 20 SPS (0x91). The amplified input is 1.8 × 2 = 3.6 V, above 3.3 V.'),measure('Expect code 4095 and OVERRANGE. This is the intended failure, not a reason to keep retrying.'),response('result','Explain why settled code 4095 with OVERRANGE is not a valid level measurement. Why would averaging not fix clipping?'),save('P2-saturation')]},
 C:{learn:'Distinguish a DAC command, register acceptance and ADC feedback; state the shared-reference limitation.',steps:[step('Prepare the loopback example','registers',[],'Click Prepare fields. This selects CH2 suggestions and a nominal reference; it does not write CONFIG or DAC registers.','Prepared-field confirmation.','Begin from documented conditions instead of carrying over the previous gain.','prepared',{prepare:true}),config('Use enabled, CH2, gain ×1, 20 SPS (0x89). CH2 is wired to the teaching DAC output.'),dac(true),measure('Expect about 1.650 V and code 2048. LT-201.PV is N/A because this is not the tank channel.'),response('result','What does Read DAC registers prove? What does CH2 feedback add? Why can a shared-reference loopback fail to establish absolute voltage accuracy?'),save('P3-loopback')]},
 D:{learn:'Establish a baseline, detect a rejected change, remove the cause, then rewrite and retest.',steps:[input(1,true),config('Establish enabled CH0, gain ×1, 20 SPS (0x81) before injecting the fault.'),measure(),fail(true),rejected(true),response('failure','Record requested and returned CONFIG values. Why does Write sent not prove the change happened?'),remove(),config('Retry enabled CH1, gain ×1, 20 SPS. You should now read back 0x85.'),measure('CH1 measures the independent 1.00 V source. LT-201.PV should be N/A; the tank level is irrelevant to this channel.'),response('recovery','Which evidence shows acceptance after recovery, and which shows the CH1 measurement?'),save('P4-recovery')]},
 E:{learn:'Apply the signal conversion and verification sequence to a new input without prepared settings.',steps:[predict('At 0.75 m, CH0, gain ×1, 20 SPS and 3.3 V: predict current (mA), shunt voltage (V) and integer ADC code. Show formulas.'),input(.75,false),config('Set the channel, gain and rate specified in I1 yourself.'),measure(),response('result','Compare predicted and observed current, voltage, code and reconstructed level. Explain any quantization difference.'),save('I1')]},
 F:{learn:'Use input range and status evidence to justify a configuration correction.',steps:[predict('At 1.50 m with gain ×2, predict whether the amplified voltage fits the 3.3 V range. Explain before testing.'),input(1.5,false),config('Set enabled CH0, gain ×2 and 20 SPS for the requested first test.'),measure(),response('failure','Record the first test’s raw code and flags. Is it usable? Choose and justify a correction before applying it.'),config('Apply your chosen usable gain. Keep CH0, the same input and 20 SPS.'),measure(),response('recovery','Compare the before/after code and flags. Explain why the correction is appropriate; refer to the input range.'),save('I2-recovery')]},
 G:{learn:'Choose a feedback path and separate register evidence from measured output evidence.',steps:[predict('For DAC code 1024 on the 12-bit 3.3 V teaching DAC, predict the voltage. Choose an ADC feedback channel and gain, and predict its code.'),step('Set nominal conditions','bench',['fault','assumed'],'Select None / nominal and a 3.3 V software reference.','Reference assumption and fault state. The tank input is not part of this test.','Document the test conditions before comparing DAC and ADC.','nominal'),config('Choose the ADC channel and gain for DAC feedback yourself. Enable the ADC and use 20 SPS.'),dac(false),measure(),response('result','Compare your prediction with the feedback. Explain what the DAC register read-back proves, what ADC feedback adds, and one limitation.'),save('I3')]},
 H:{learn:'Use a baseline and read-back evidence to diagnose a configuration failure and demonstrate recovery.',steps:[step('Set the baseline conditions','bench',['fault','assumed','pot'],'Select None / nominal, a 3.3 V reference and CH1 test voltage 1.00 V.','These are test conditions, not evidence that the ADC is configured.','A repeatable baseline makes the later failed request interpretable.','nominal'),config('Establish enabled CH0, gain ×1, 20 SPS.'),measure(),fail(false),rejected(false),response('failure','Record intended and returned CONFIG values. What failed, and what observation supports your conclusion?'),remove(),config('Retry the intended CH1 configuration and check its acceptance.'),measure(),response('recovery','Identify the evidence for successful recovery. Why is merely removing the fault insufficient?'),save('I4-recovery')]}
 };
 const metadata={A:{phase:'practice',title:'A · One known input, end to end',prepare:{mux:0,gain:0}},B:{phase:'practice',title:'B · Gain and validity',prepare:{mux:0,gain:1}},C:{phase:'practice',title:'C · One DAC loopback',prepare:{mux:2,gain:0}},D:{phase:'practice',title:'D · Lost write and recovery',prepare:{mux:0,gain:0}},E:{phase:'independent',title:'I1 · A new known input'},F:{phase:'independent',title:'I2 · Diagnose an unusable reading'},G:{phase:'independent',title:'I3 · DAC feedback'},H:{phase:'independent',title:'I4 · Configuration failure'}};
 for(const [key,plan]of Object.entries(plans)){Object.assign(plan,metadata[key]);if(!['practice','independent'].includes(plan.phase))throw Error('Missing or invalid phase for '+key);plan.label=plan.steps.find(s=>s.gate==='save').label;}
 const finish={title:'Save locally · Upload to Moodle yourself',learn:'Download the readable HTML report and JSON evidence, then upload them to Moodle yourself. Nothing is submitted by this page.',steps:['Check I1–I4 predictions, explanations, and checkpoints.','Complete two asset rows, one data-flow row, and your final discussion/limitation.','Download report (HTML) and evidence (JSON). Review both; use the browser print option if a PDF is required.','Upload your files to Moodle yourself. Downloads and browser autosave are not submissions.']};
 const tasks=Object.fromEntries(Object.entries(plans).map(([key,p])=>[key,{title:p.title,goal:p.learn,steps:p.steps.map(s=>s.instruction),pass:'Complete the listed steps, save '+p.label+', and explain your evidence.',target:p.steps[0].area}]));
 tasks.Submit={title:finish.title,goal:finish.learn,steps:finish.steps,pass:'Review and save your report and evidence locally.',target:'records'};
 function inputIssues(step,lab){
  const issues=[];
  if(step.gate==='input'&&Math.abs(Number(lab.level)-step.level)>1e-9)issues.push('Set tank level to '+step.level.toFixed(2)+' m (currently '+Number(lab.level).toFixed(2)+' m).');
  if(!Number.isFinite(Number(lab.level))&&step.gate==='input')issues.push('Enter a valid tank level.');
  if(lab.fault!=='none')issues.push('Set Fault injection to None / nominal (currently '+lab.fault+').');
  if(Math.abs(Number(lab.assumedRef)-3.3)>1e-9||!Number.isFinite(Number(lab.assumedRef)))issues.push('Set Software reference assumption to 3.3 V.');
  return issues;
 }
 function evaluate(step,ctx){
  const {lab,actions,entry,proposed,writeBox,predictions,responses}=ctx;
  const recent=actions.filter(a=>a.seq>entry.action);
  const last=id=>recent.filter(a=>a.id===id).at(-1);
  const sample=lab.samples.at(-1);
  const fresh=sample&&sample.config===('0x'+lab.config.toString(16).toUpperCase().padStart(2,'0'))&&sample.physical_level_m===lab.level&&sample.fault===lab.fault&&sample.assumed_reference_V===lab.assumedRef&&sample.input_voltage_V===+lab.inputVoltage.toFixed(6);
  const sequence=()=>{const c=last('copy'),w=last('write'),r=last('configRead');return c&&w&&r&&c.seq<w.seq&&w.seq<r.seq&&w.request===proposed&&writeBox===proposed&&r.config===lab.config&&r.readback==='CONFIG read-back = 0x'+lab.config.toString(16).toUpperCase().padStart(2,'0');};
  switch(step.gate){
   case 'input':return inputIssues(step,lab).length===0&&(!step.prepare||!!last('prepare'));
   case 'prepared':return !!last('prepare');
   case 'nominal':return inputIssues(step,lab).length===0;
   case 'id':return last('idRead')?.readback==='ID = 0x42';
   case 'config':return !!sequence()&&lab.config===proposed;
   case 'rejected':return !!sequence()&&lab.fault==='drop'&&lab.config!==proposed&&!!last('write')?.dropped;
   case 'dac':{const w=last('dacWrite'),r=last('dacRead');return !!w&&!!r&&w.seq<r.seq&&w.dac===step.dac&&r.readback==='DAC = '+step.dac&&lab.dac===step.dac;}
   case 'fault':return lab.fault===step.fault&&(step.fault!=='none'||lab.pot===1);
   case 'sample':return !!last('three')&&!!fresh&&sample.sample_id>entry.sample&&sample.settled;
   case 'prediction':return predictions.some(p=>p.task===ctx.task&&p.action_seq>entry.action);
   case 'response':return responses.some(r=>r.task===ctx.task&&r.key===step.responseKey&&r.action_seq>entry.action&&r.text.trim());
   case 'save':return lab.saved.length>entry.saved&&lab.saved.at(-1).assignment===ctx.task&&!!fresh&&lab.saved.at(-1).sample_id===sample.sample_id;
   default:return false;
  }
 }
 function expectations(){return Object.fromEntries(Object.entries(plans).map(([key,p])=>[key,{title:p.title,phase:p.phase,prediction_required:p.steps.some(s=>s.gate==='prediction'),checkpoint_required:p.steps.some(s=>s.gate==='save'),responses:p.steps.filter(s=>s.gate==='response').map(s=>({key:s.responseKey,title:s.responsePrompt}))}]));}
 function taskKeys(phase){return Object.keys(plans).filter(k=>!phase||plans[k].phase===phase);}
 root.LabSteps={plans,tasks,evaluate,inputIssues,expectations,taskKeys};
 if(typeof module!=='undefined')module.exports=root.LabSteps;
})(typeof window!=='undefined'?window:globalThis);
